// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace MSTest.Analyzers;

#pragma warning disable RS1035 // Roslyn 3.11 does not expose IIncrementalGenerator.
[Generator(LanguageNames.CSharp, LanguageNames.VisualBasic)]
internal sealed class MSTestHostInjectionMetadataGenerator : ISourceGenerator
{
    private const string HostInjectionContainingType = "Microsoft.Extensions.DependencyInjection.MSTestHostingServiceCollectionExtensions";
    private const string HostInjectionMethod = "AddMSTestTestClassInjection";
    private const string HostInjectionAssembly = "MSTest.Extensions.Hosting";

    public void Initialize(GeneratorInitializationContext context)
        => context.RegisterForSyntaxNotifications(static () => new InvocationSyntaxReceiver());

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not InvocationSyntaxReceiver receiver
            || !receiver.Candidates.Any(candidate =>
                context.Compilation.GetSemanticModel(candidate.SyntaxTree).GetOperation(candidate) is IInvocationOperation invocation
                && IsHostInjectionMethod(invocation.TargetMethod)))
        {
            return;
        }

        string source = context.Compilation.Language == LanguageNames.VisualBasic
            ? """
                ' <auto-generated/>
                <Assembly: System.Reflection.AssemblyMetadataAttribute("MSTestHostTestClassInjectionEnabled", "true")>
                """
            : """
                // <auto-generated/>
                [assembly: System.Reflection.AssemblyMetadataAttribute("MSTestHostTestClassInjectionEnabled", "true")]
                """;
        string extension = context.Compilation.Language == LanguageNames.VisualBasic ? "vb" : "cs";
        context.AddSource(
            $"MSTestHostTestClassInjectionMetadata.g.{extension}",
            SourceText.From(source, Encoding.UTF8));
    }

    private static bool IsHostInjectionMethod(IMethodSymbol method)
    {
        IMethodSymbol targetMethod = method.ReducedFrom ?? method;
        return targetMethod.Name == HostInjectionMethod
            && targetMethod.ContainingAssembly.Name == HostInjectionAssembly
            && targetMethod.ContainingType.ToDisplayString() == HostInjectionContainingType
            && targetMethod.Parameters is [IParameterSymbol { Type.SpecialType: SpecialType.None } parameter]
            && parameter.Type.ToDisplayString() == "Microsoft.Extensions.DependencyInjection.IServiceCollection"
            && targetMethod.ReturnType.ToDisplayString() == "Microsoft.Extensions.DependencyInjection.IServiceCollection";
    }

    private sealed class InvocationSyntaxReceiver : ISyntaxReceiver
    {
        public List<SyntaxNode> Candidates { get; } = [];

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode.GetType().Name == "InvocationExpressionSyntax"
                && syntaxNode.ToString().Contains(HostInjectionMethod, StringComparison.Ordinal))
            {
                Candidates.Add(syntaxNode);
            }
        }
    }
}
#pragma warning restore RS1035
