// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Microsoft.Testing.Platform.IPC.SourceGeneration.Helpers;

internal static class StringBuilderExtensions
{
    public static void AppendAutoGeneratedHeader(this IndentedStringBuilder builder)
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.IO;");
        builder.AppendLine("using System.Text;");
        builder.AppendLine("using Microsoft.Testing.Platform.IPC;");
        builder.AppendLine("using Microsoft.Testing.Platform.IPC.Serializers;");
    }
}
