id:
name: LabelManagement.IssueClosed
description: Handlers when an issue gets closed
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Remove labels when an issue is closed
        if:
          - payloadType: Issues
          - isAction:
              action: Closed
        then:
          - removeLabel:
              label: 'needs/triage'
          - removeLabel:
              label: 'needs/attention'
          - removeLabel:
              label: 'needs/author-feedback'
          - removeLabel:
              label: 'help wanted'
      - description: Remove labels when a pull request is closed
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Closed
        then:
          - removeLabel:
              label: 'needs/attention'
          - removeLabel:
              label: 'needs/author-feedback'
onFailure:
onSuccess:
