id:
name: LabelManagement.IssueUpdated
description: Handlers when an issue is updated but not closed
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: >-
          Remove "state/stale" when a pull request or issue is updated
        if:
          - or:
              - payloadType: Pull_Request
              - payloadType: Pull_Request_Review
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
              - payloadType: Issues
          - not:
              isAction:
                action: Closed
          - hasLabel:
              label: "state/stale"
        then:
          - removeLabel:
              label: "state/stale"
        # The policy service should not trigger itself here, or else the label would be removed immediately after being added
        triggerOnOwnActions: False
      - description: Clean email replies on every comment
        if:
          - payloadType: Issue_Comment
        then:
          - cleanEmailReply
      - description: Remove "help wanted" label when an issue goes into PR
        if:
          - payloadType: Issues
          - labelAdded:
              label: state/in-pr
          - hasLabel:
              label: "help wanted"
        then:
          - removeLabel:
              label: "help wanted"
      - description: >-
          If an author responds to an issue which needs author feedback
          * Remove the "needs/author-feedback" Label
          * Add the "needs/attention" Label
        if:
          - or:
              - payloadType: Pull_Request_Review
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
          - isActivitySender:
              issueAuthor: True
          - hasLabel:
              label: "needs/author-feedback"
          - not:
              isAction:
                action: Synchronize
        then:
          - removeLabel:
              label: "needs/author-feedback"
          - addLabel:
              label: "needs/attention"
      - description: >-
          If team members respond to an issue which needs attention
          * Remove the "needs/attention" Label
        if:
          - or:
              - payloadType: Pull_Request_Review
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
          - isActivitySender:
              issueAuthor: True
          - hasLabel:
              label: "needs/attention"
          - not:
              isAction:
                action: Synchronize
          - or:
            - activitySenderHasAssociation:
                association: Member
            - activitySenderHasAssociation:
                association: Owner
            - activitySenderHasAssociation:
                association: Collaborator
        then:
          - removeLabel:
              label: "needs/attention"
      - description: >-
          If team members respond to an issue which needs triage
          * Remove the "needs/triage" Label
        if:
          - or:
              - payloadType: Pull_Request_Review
              - payloadType: Pull_Request_Review_Comment
              - payloadType: Issue_Comment
          - isActivitySender:
              issueAuthor: True
          - hasLabel:
              label: "needs/triage"
          - not:
              isAction:
                action: Synchronize
          - or:
            - activitySenderHasAssociation:
                association: Member
            - activitySenderHasAssociation:
                association: Owner
            - activitySenderHasAssociation:
                association: Collaborator
        then:
          - removeLabel:
              label: "needs/triage"
      - description: >-
          When changes are requested on a pull request
          * Disable automerge
          * Assign to the author
          * Label with "needs/author-feedback"
        if:
          - payloadType: Pull_Request_Review
          - isAction:
              action: Submitted
          - isReviewState:
              reviewState: Changes_requested
        then:
          - disableAutoMerge
          - assignTo:
              author: True
          - addLabel:
              label: "needs/author-feedback"
      - description: Sync labels from issues on all pull request events
        if:
          - payloadType: Pull_Request
        then:
          - labelSync:
              pattern: "area/"
          - labelSync:
              pattern: "type/"
          - inPrLabel:
              label: state/in-pr
onFailure:
onSuccess:
