#!/usr/bin/env python3
"""
Audit GitHub Actions `uses:` pins across the workflows in this repository.

Generated agentic-workflow files (`*.lock.yml`, plus the gh-aw-generated
`agentic_commands.yml` / `agentics-maintenance.yml`) are produced by
`gh aw compile`. A locally installed `gh aw` build can silently emit pins that
disagree with the repo-aligned values recorded in `.github/aw/actions-lock.json`
-- for example downgrading `actions/checkout` or replacing an immutable SHA with
a mutable tag -- and because the damage lands in generated files it easily rides
along unnoticed in an unrelated pull request (see microsoft/testfx#10258).

This script is a deterministic, offline guard for exactly that failure mode.
It enforces three rules:

    R1 (generated files) Every `uses:` reference must be pinned to a 40-character
       commit SHA. A mutable tag or branch is rejected. Generated files are
       classified by filename (`*.lock.yml` plus the gh-aw-generated
       `agentic_commands.yml` / `agentics-maintenance.yml`), with header banners
       as a secondary net.
    R2 (all files)       When an action repository appears in
       `.github/aw/actions-lock.json`, every SHA-pinned reference to it must use
       the locked SHA and carry a trailing `# vX.Y.Z` comment naming the locked
       version. A missing label fails too, so the check cannot be evaded by
       deleting it.
    R3 (all files)       An action repository must resolve to a single SHA across
       every scanned file. This catches drift for actions the compiler injects
       but that are absent from `actions-lock.json`.

The audit fails closed: a missing, malformed, or empty `actions-lock.json` is an
error rather than a licence to skip R2, since R1 and R3 alone both pass when
every occurrence of an action is rewritten to the same stale SHA.

References inside a workflow's generated header (the `# Custom actions used:`
block) are audited alongside the live `uses:` steps, because the corruption shows
up there too. The machine-readable `# gh-aw-manifest:` JSON header is *not*
audited: it is compiler bookkeeping copied from `actions-lock.json` at compile
time rather than an executable reference, so it self-heals on the next recompile.

Usage:
    python .github/scripts/check_action_pins.py          # audit, exit 1 on failure
    python .github/scripts/check_action_pins.py --list   # print the resolved pin table
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
WORKFLOW_DIR = REPO_ROOT / ".github" / "workflows"
ACTIONS_DIR = REPO_ROOT / ".github" / "actions"
ACTIONS_LOCK_PATH = REPO_ROOT / ".github" / "aw" / "actions-lock.json"

SHA_RE = re.compile(r"^[0-9a-f]{40}$")
ACTION_REF_RE = re.compile(r"^[A-Za-z0-9._-]+(?:/[A-Za-z0-9._-]+)+@\S+$")
USES_RE = re.compile(
    r"""^\s*(?:-\s*)?uses:\s*['"]?(?P<ref>[^'"\s]+)['"]?\s*(?:\#\s*(?P<comment>.*?))?\s*$"""
)
# `#   - actions/checkout@<sha> # v7.0.1` inside the generated header block.
HEADER_ACTION_RE = re.compile(
    r"""^#\s+-\s+(?P<ref>\S+@\S+?)\s*(?:\#\s*(?P<comment>.*?))?\s*$"""
)
MANIFEST_RE = re.compile(r"^#\s*gh-aw-manifest:")
# A file is "generated" when its name says so -- filename classification is
# deterministic and cannot be defeated by a compiler changing its header text.
# gh-aw emits several distinct banners (`generated by gh-aw`,
# `generated by pkg/workflow/maintenance_workflow.go`, ...), so the header
# markers below are only a secondary net for generated files added later.
GENERATED_SUFFIX = ".lock.yml"
GENERATED_FILENAMES = frozenset({"agentic_commands.yml", "agentics-maintenance.yml"})
GENERATED_MARKERS = ("# gh-aw-manifest:", "automatically generated by")
HEADER_ACTIONS_SECTION = "# Custom actions used:"


@dataclass(frozen=True)
class Reference:
    """A single `uses:`-style action reference discovered in a workflow file."""

    repo: str
    ref: str
    comment_version: str | None
    path: Path
    line: int
    generated: bool

    @property
    def location(self) -> str:
        return f"{self.path.relative_to(REPO_ROOT).as_posix()}:{self.line}"

    @property
    def is_sha_pinned(self) -> bool:
        return SHA_RE.match(self.ref) is not None


class LockFileError(RuntimeError):
    """Raised when `.github/aw/actions-lock.json` is missing or unusable."""


def load_actions_lock() -> dict[str, tuple[str, str]]:
    """Map action repository -> (version, sha) from .github/aw/actions-lock.json.

    Fails closed. The lock file is R2's only source of truth, so treating an
    absent or empty one as "nothing to enforce" would silently downgrade the
    audit to R1 + R3 -- and those two pass happily when every occurrence of an
    action is rewritten to the same stale SHA. Deleting the lock must therefore
    be an error, not a way to weaken the check.
    """
    if not ACTIONS_LOCK_PATH.exists():
        raise LockFileError(f"{ACTIONS_LOCK_PATH.relative_to(REPO_ROOT).as_posix()} is missing")

    try:
        data = json.loads(ACTIONS_LOCK_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise LockFileError(
            f"{ACTIONS_LOCK_PATH.relative_to(REPO_ROOT).as_posix()} is not valid JSON: {error}"
        ) from error

    locked: dict[str, tuple[str, str]] = {}
    for entry in data.get("entries", {}).values():
        repo = entry.get("repo")
        sha = entry.get("sha")
        version = entry.get("version", "")
        if repo and sha:
            locked[repo] = (version, sha)

    if not locked:
        raise LockFileError(
            f"{ACTIONS_LOCK_PATH.relative_to(REPO_ROOT).as_posix()} contains no usable entries"
        )

    return locked


def split_ref(raw: str) -> tuple[str, str] | None:
    """Split `owner/repo@ref` into its parts, or return None when not an action ref."""
    if raw.startswith(("./", "../", ".\\", "docker://")) or raw.startswith("${{"):
        return None
    if not ACTION_REF_RE.match(raw):
        return None

    repo, _, ref = raw.partition("@")
    if not repo or not ref or ref.startswith("sha256:"):
        return None

    return repo, ref


def normalize_comment_version(comment: str | None) -> str | None:
    """Extract the version token from a trailing comment such as `v9.0.0 (source v9)`."""
    if not comment:
        return None

    token = comment.strip().split()[0] if comment.strip() else ""
    return token or None


def is_generated(path: Path, text: str) -> bool:
    """Classify a workflow as compiler-generated.

    Filename classification is primary: `agentics-maintenance.yml` carries a
    `generated by pkg/workflow/maintenance_workflow.go` banner and no
    `gh-aw-manifest` header, so header sniffing alone would silently exempt it
    from R1 even though it holds a dozen `github/gh-aw-actions/setup*` pins --
    exactly the references #10258 reports being un-pinned.
    """
    if path.name.endswith(GENERATED_SUFFIX) or path.name in GENERATED_FILENAMES:
        return True

    return any(marker in text for marker in GENERATED_MARKERS)


def collect_references(path: Path) -> list[Reference]:
    text = path.read_text(encoding="utf-8")
    generated = is_generated(path, text)
    references: list[Reference] = []
    in_header_actions = False

    for lineno, line in enumerate(text.splitlines(), start=1):
        if MANIFEST_RE.match(line):
            # Compiler bookkeeping, not an executable reference. See module docstring.
            continue

        if line.startswith("#"):
            if line.rstrip() == HEADER_ACTIONS_SECTION:
                in_header_actions = True
                continue
            if in_header_actions:
                header_match = HEADER_ACTION_RE.match(line)
                if header_match is None:
                    in_header_actions = False
                    continue
                parts = split_ref(header_match.group("ref"))
                if parts is not None:
                    references.append(
                        Reference(
                            repo=parts[0],
                            ref=parts[1],
                            comment_version=normalize_comment_version(header_match.group("comment")),
                            path=path,
                            line=lineno,
                            generated=generated,
                        )
                    )
            continue

        in_header_actions = False
        uses_match = USES_RE.match(line)
        if uses_match is None:
            continue

        parts = split_ref(uses_match.group("ref"))
        if parts is None:
            continue

        references.append(
            Reference(
                repo=parts[0],
                ref=parts[1],
                comment_version=normalize_comment_version(uses_match.group("comment")),
                path=path,
                line=lineno,
                generated=generated,
            )
        )

    return references


def iter_workflow_files() -> list[Path]:
    files: list[Path] = []
    for directory, patterns in ((WORKFLOW_DIR, ("*.yml", "*.yaml")), (ACTIONS_DIR, ("**/*.yml", "**/*.yaml"))):
        if not directory.exists():
            continue
        for pattern in patterns:
            files.extend(directory.glob(pattern))

    return sorted(set(files))


def audit(references: list[Reference], locked: dict[str, tuple[str, str]]) -> list[str]:
    errors: list[str] = []

    # R1: generated files must never carry a mutable reference.
    for reference in references:
        if reference.generated and not reference.is_sha_pinned:
            errors.append(
                f"{reference.location}: `{reference.repo}@{reference.ref}` is not pinned to a commit SHA. "
                "Generated workflows must pin every action to an immutable SHA; recompile with the "
                "toolchain pinned in .github/aw/actions-lock.json."
            )

    # R2: SHA-pinned references must agree with .github/aw/actions-lock.json.
    for reference in references:
        if not reference.is_sha_pinned:
            continue
        expected = locked.get(reference.repo)
        if expected is None:
            continue

        expected_version, expected_sha = expected
        if reference.ref != expected_sha:
            errors.append(
                f"{reference.location}: `{reference.repo}` is pinned to {reference.ref} "
                f"({reference.comment_version or 'unknown version'}) but .github/aw/actions-lock.json "
                f"records {expected_sha} ({expected_version})."
            )
        elif expected_version and reference.comment_version != expected_version:
            # A missing label is a failure too: dropping `# vX.Y.Z` would otherwise
            # let a mislabelled pin through by simply deleting the evidence.
            actual = reference.comment_version or "no version label"
            errors.append(
                f"{reference.location}: `{reference.repo}` is pinned to the expected SHA but is labelled "
                f"{actual} instead of {expected_version}."
            )

    # R3: every action must resolve to a single SHA repo-wide.
    by_repo: dict[str, dict[str, list[Reference]]] = defaultdict(lambda: defaultdict(list))
    for reference in references:
        if reference.is_sha_pinned:
            by_repo[reference.repo][reference.ref].append(reference)

    for repo, shas in sorted(by_repo.items()):
        if len(shas) < 2:
            continue
        details = []
        for sha, refs in sorted(shas.items()):
            versions = sorted({ref.comment_version for ref in refs if ref.comment_version})
            label = f" ({', '.join(versions)})" if versions else ""
            sample = ", ".join(ref.location for ref in refs[:3])
            more = f", +{len(refs) - 3} more" if len(refs) > 3 else ""
            details.append(f"    {sha}{label}: {sample}{more}")
        errors.append(
            f"`{repo}` resolves to {len(shas)} different SHAs across the workflows:\n" + "\n".join(details)
        )

    return errors


def print_pin_table(references: list[Reference]) -> None:
    by_repo: dict[str, set[tuple[str, str]]] = defaultdict(set)
    for reference in references:
        by_repo[reference.repo].add((reference.ref, reference.comment_version or ""))

    for repo, pins in sorted(by_repo.items()):
        for ref, version in sorted(pins):
            suffix = f" # {version}" if version else ""
            print(f"{repo}@{ref}{suffix}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--list", action="store_true", help="Print the resolved pin table and exit.")
    args = parser.parse_args(argv)

    files = iter_workflow_files()
    if not files:
        print(f"error: no workflow files found under {WORKFLOW_DIR}", file=sys.stderr)
        return 1

    references: list[Reference] = []
    for path in files:
        references.extend(collect_references(path))

    if args.list:
        print_pin_table(references)
        return 0

    try:
        locked = load_actions_lock()
    except LockFileError as error:
        print(f"error: {error}.", file=sys.stderr)
        print(
            "The actions lock is the only source of truth for the SHA every action must "
            "resolve to, so the audit fails closed rather than silently skipping that check. "
            "Restore the file (it is generated by `gh aw compile`) and re-run.",
            file=sys.stderr,
        )
        return 1

    errors = audit(references, locked)
    if errors:
        print(f"Action pin audit failed with {len(errors)} problem(s):\n", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        print(
            "\nGenerated `.lock.yml` files must be compiled with the toolchain pinned in "
            "`.github/aw/actions-lock.json`. A locally installed `gh aw` build can emit stale "
            "pins (microsoft/testfx#10258); recompile on the pinned toolchain, or re-run "
            "`gh aw compile` after `gh extension upgrade aw`, and commit the corrected lock files.",
            file=sys.stderr,
        )
        return 1

    print(f"Action pin audit passed: {len(references)} reference(s) across {len(files)} file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
