// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1611:Element parameters must be documented", Justification = "Exclusion", Scope = "member", Target = "~M:Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestContextImplementation.TryGetPropertyValue(System.String,System.Object@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1611:Element parameters must be documented", Justification = "Exclusion", Scope = "member", Target = "~M:Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestContextImplementation.AddProperty(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Exclusion", Scope = "type", Target = "~T:Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestContextImplementation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1514:Element documentation header must be preceded by blank line", Justification = "Exclusion", Scope = "member", Target = "~P:Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestContextImplementation.FullyQualifiedTestClassName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1611:Element parameters must be documented", Justification = "Exclusion", Scope = "member", Target = "~M:Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestContextImplementation.SetOutcome(Microsoft.VisualStudio.TestTools.UnitTesting.UnitTestOutcome)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1615:Element return value must be documented", Justification = "Exclusion", Scope = "member", Target = "~M:Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestContextImplementation.TryGetPropertyValue(System.String,System.Object@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single class", Justification = "Exclusion", Scope = "type", Target = "~T:Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestContextPropertyStrings")]