//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Testing.Platform.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlatformResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlatformResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Testing.Platform.Resources.PlatformResources", typeof(PlatformResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the default json configuration.
        /// </summary>
        internal static string ConfigurationManagerCannotFindDefaultJsonConfigurationErrorMessage {
            get {
                return ResourceManager.GetString("ConfigurationManagerCannotFindDefaultJsonConfigurationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate key &apos;{0}&apos; was found.
        /// </summary>
        internal static string JsonConfigurationFileParserDuplicateKeyErrorMessage {
            get {
                return ResourceManager.GetString("JsonConfigurationFileParserDuplicateKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-level JSON element must be an object. Instead, &apos;{0}&apos; was found.
        /// </summary>
        internal static string JsonConfigurationFileParserTopLevelElementIsNotAnObjectErrorMessage {
            get {
                return ResourceManager.GetString("JsonConfigurationFileParserTopLevelElementIsNotAnObjectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported JSON token &apos;{0}&apos; was found.
        /// </summary>
        internal static string JsonConfigurationFileParserUnsupportedTokenErrorMessage {
            get {
                return ResourceManager.GetString("JsonConfigurationFileParserUnsupportedTokenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find service of type &apos;{0}&apos;.
        /// </summary>
        internal static string ServiceProviderCannotFindServiceErrorMessage {
            get {
                return ResourceManager.GetString("ServiceProviderCannotFindServiceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type &apos;{0}&apos; is already registered.
        /// </summary>
        internal static string ServiceProviderServiceAlreadyRegistered {
            get {
                return ResourceManager.GetString("ServiceProviderServiceAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances of type &apos;ITestFramework&apos; should not be registered through the service provider but through &apos;ITestApplicationBuilder.RegisterTestFramework&apos;.
        /// </summary>
        internal static string ServiceProviderShouldNotRegisterTestFramework {
            get {
                return ResourceManager.GetString("ServiceProviderShouldNotRegisterTestFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has already been built.
        /// </summary>
        internal static string TestApplicationBuilderApplicationAlreadyRegistered {
            get {
                return ResourceManager.GetString("TestApplicationBuilderApplicationAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test framework adapter factory has already been registered.
        /// </summary>
        internal static string TestApplicationBuilderFrameworkAdapterFactoryAlreadyRegisteredErrorMessage {
            get {
                return ResourceManager.GetString("TestApplicationBuilderFrameworkAdapterFactoryAlreadyRegisteredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test framework capabilities factory has already been registered.
        /// </summary>
        internal static string TestApplicationBuilderTestFrameworkCapabilitiesAlreadyRegistered {
            get {
                return ResourceManager.GetString("TestApplicationBuilderTestFrameworkCapabilitiesAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test framework adapter has not been registered. Use &apos;RegisterTestFrameworkAdapter&apos; to register it.
        /// </summary>
        internal static string TestApplicationBuilderTestFrameworkNotRegistered {
            get {
                return ResourceManager.GetString("TestApplicationBuilderTestFrameworkNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine the result of the test application execution.
        /// </summary>
        internal static string TestApplicationResultDescription {
            get {
                return ResourceManager.GetString("TestApplicationResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test application result.
        /// </summary>
        internal static string TestApplicationResultDisplayName {
            get {
                return ResourceManager.GetString("TestApplicationResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTest mode only supports a single TestApplicationBuilder per process.
        /// </summary>
        internal static string TestApplicationVSTestModeTooManyBuilders {
            get {
                return ResourceManager.GetString("TestApplicationVSTestModeTooManyBuilders", resourceCulture);
            }
        }
    }
}
