// <auto-generated />

#if !NET10_0_OR_GREATER
using Microsoft.CodeAnalysis;

namespace System.Runtime.CompilerServices;

[AttributeUsage(AttributeTargets.Class, Inherited = false)]
[Embedded]
internal sealed class CompilerLoweringPreserveAttribute : Attribute;
#endif
