// <auto-generated />

#if !NET10_0_OR_GREATER
using Microsoft.CodeAnalysis;

namespace System.Runtime.CompilerServices;

[AttributeUsage(AttributeTargets.Class, Inherited = false)]
[Embedded]
internal sealed class CompilerLoweringPreserveAttribute : Attribute;
#else
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.CompilerLoweringPreserveAttribute))]
#endif
