// <auto-generated />

#if !NETCOREAPP && !EXCLUDE_OS_POLYFILL

using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

using Microsoft.CodeAnalysis;

namespace Polyfills;

internal static partial class Polyfill
{
    extension(OperatingSystem)
    {
        public static bool IsWasi()
            => RuntimeInformation.IsOSPlatform(OSPlatform.Create("WASI"));

        public static bool IsAndroid()
            => RuntimeInformation.IsOSPlatform(OSPlatform.Create("ANDROID"));

        public static bool IsIOS()
            => RuntimeInformation.IsOSPlatform(OSPlatform.Create("IOS"));

        public static bool IsTvOS()
            => RuntimeInformation.IsOSPlatform(OSPlatform.Create("TVOS"));

        public static bool IsBrowser()
            => RuntimeInformation.IsOSPlatform(OSPlatform.Create("BROWSER"));
    }
}
#endif
