<?xml version="1.0" encoding="utf-8" ?>
<Project>
  <ItemGroup>
    <!-- Declare our capabilities early so project-system consumers can observe them during evaluation. -->
    <_TestingPlatformProjectCapability Include="TestingPlatformServer">
      <TestingPlatformCapabilityOwner>Microsoft.Testing.Platform</TestingPlatformCapabilityOwner>
    </_TestingPlatformProjectCapability>

    <!-- Old capability expected by VS/VSCode -->
    <_TestingPlatformProjectCapability Include="TestContainer">
      <TestingPlatformCapabilityOwner>Microsoft.Testing.Platform</TestingPlatformCapabilityOwner>
    </_TestingPlatformProjectCapability>

    <ProjectCapability Include="@(_TestingPlatformProjectCapability)" />

    <!-- For VS Test Explorer -->
    <ProjectCapability Include="TestingPlatformServer.ExitOnProcessExitCapability">
      <Description>--exit-on-process-exit: Close the test process if specific process exits. Process PID must be provided.</Description>
    </ProjectCapability>
    <ProjectCapability Include="TestingPlatformServer.UseListTestsOptionForDiscoveryCapability">
      <Description>The implementation handle the --list-tests in --server [jsonrpc] during discovery</Description>
    </ProjectCapability>
  </ItemGroup>
</Project>
