// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Runtime.Loader;
using System.Text.Json;

using Microsoft.Build.Framework;

using Moq;

namespace Microsoft.Testing.Platform.MSBuild.UnitTests;

[TestClass]
public sealed class MSBuildTests
{
    private readonly Mock<IBuildEngine> _buildEngine = new();
    private readonly List<BuildErrorEventArgs> _errors = [];
    private readonly List<BuildMessageEventArgs> _messages = [];

    public MSBuildTests()
    {
        _buildEngine.Setup(x => x.LogErrorEvent(It.IsAny<BuildErrorEventArgs>())).Callback<BuildErrorEventArgs>(e => _errors.Add(e));
        _buildEngine.Setup(x => x.LogMessageEvent(It.IsAny<BuildMessageEventArgs>())).Callback<BuildMessageEventArgs>(e => _messages.Add(e));
    }

    [TestMethod]
    public void Verify_Correct_Registration_Order_For_WellKnown_Extensions()
    {
        InMemoryFileSystem inMemoryFileSystem = new();
        TestingPlatformEntryPointTask testingPlatformEntryPoint = new(inMemoryFileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformEntryPointSourcePath = new CustomTaskItem("obj/entryPointFile"),
            Language = new CustomTaskItem("C#"),
            RootNamespace = "SomeNamespace",
        };

        testingPlatformEntryPoint.Execute();

        string expectedSourceOrder = """
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Microsoft.Testing.Platform.MSBuild
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomeNamespace
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class MicrosoftTestingPlatformApplication
    {
        public static async global::System.Threading.Tasks.Task<int> RunAsync(string[] args)
        {
            global::Microsoft.Testing.Platform.Builder.ITestApplicationBuilder builder = await global::Microsoft.Testing.Platform.Builder.TestApplication.CreateBuilderAsync(args);
            global::SomeNamespace.SelfRegisteredExtensions.AddSelfRegisteredExtensions(builder, args);
            using (global::Microsoft.Testing.Platform.Builder.ITestApplication app = await builder.BuildAsync())
            {
                return await app.RunAsync();
            }
        }
    }

    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class MicrosoftTestingPlatformEntryPoint
    {
        public static global::System.Threading.Tasks.Task<int> Main(string[] args)
            => MicrosoftTestingPlatformApplication.RunAsync(args);
    }
}
""";

        Assert.AreEqual(expectedSourceOrder, inMemoryFileSystem.Files["obj/entryPointFile"]);
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    public void EntryPointTask_Generates_Reusable_Application_Helper_Without_Main()
    {
        InMemoryFileSystem inMemoryFileSystem = new();
        TestingPlatformEntryPointTask testingPlatformEntryPoint = new(inMemoryFileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformEntryPointSourcePath = new CustomTaskItem("obj/applicationHelperFile"),
            Language = new CustomTaskItem("C#"),
            RootNamespace = "SomeNamespace",
            GenerateEntryPoint = false,
        };

        Assert.IsTrue(testingPlatformEntryPoint.Execute());

        string generatedSource = inMemoryFileSystem.Files["obj/applicationHelperFile"]!;
        Assert.Contains("internal static class MicrosoftTestingPlatformApplication", generatedSource);
        Assert.Contains("RunAsync(string[] args)", generatedSource);
        Assert.DoesNotContain("class MicrosoftTestingPlatformEntryPoint", generatedSource);
        Assert.DoesNotContain(" Main(", generatedSource);
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    public void EntryPointTask_Preserves_Global_FSharp_EntryPoint_Without_RootNamespace()
    {
        InMemoryFileSystem inMemoryFileSystem = new();
        TestingPlatformEntryPointTask testingPlatformEntryPoint = new(inMemoryFileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformEntryPointSourcePath = new CustomTaskItem("obj/applicationHelperFile.fs"),
            Language = new CustomTaskItem("F#"),
        };

        Assert.IsTrue(testingPlatformEntryPoint.Execute());

        string generatedSource = inMemoryFileSystem.Files["obj/applicationHelperFile.fs"]!;
        Assert.Contains("module internal MicrosoftTestingPlatformApplication", generatedSource);
        Assert.Contains("module MicrosoftTestingPlatformEntryPoint", generatedSource);
        Assert.Contains("[<EntryPoint>]", generatedSource);
        Assert.DoesNotContain("namespace Microsoft.TestingPlatform", generatedSource);
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    public void EntryPointTask_GloballyQualifies_FSharp_HostFactory_Without_RootNamespace()
    {
        InMemoryFileSystem inMemoryFileSystem = new();
        TestingPlatformEntryPointTask testingPlatformEntryPoint = new(inMemoryFileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformEntryPointSourcePath = new CustomTaskItem("obj/applicationHelperFile.fs"),
            Language = new CustomTaskItem("F#"),
            HostFactory = "Contoso.Tests.TestHost.CreateHost",
        };

        Assert.IsTrue(testingPlatformEntryPoint.Execute());

        string generatedSource = inMemoryFileSystem.Files["obj/applicationHelperFile.fs"]!;
        Assert.Contains("let! host = global.Contoso.Tests.TestHost.CreateHost()", generatedSource);
        Assert.DoesNotContain("namespace Microsoft.TestingPlatform", generatedSource);
        Assert.IsEmpty(_errors);
    }

    [DataRow("C#", "obj/applicationHelperFile.cs", "global::Microsoft.Extensions.Hosting.IHost host = await global::Contoso.Tests.TestHost.CreateHost();")]
    [DataRow("VB", "obj/applicationHelperFile.vb", "Dim host As Global.Microsoft.Extensions.Hosting.IHost = Await Global.Contoso.Tests.TestHost.CreateHost()")]
    [DataRow("F#", "obj/applicationHelperFile.fs", "let! host = global.Contoso.Tests.TestHost.CreateHost()")]
    [TestMethod]
    public void EntryPointTask_Generates_Hosted_Application_For_All_Supported_Languages(string language, string sourcePath, string expectedFactoryCall)
    {
        InMemoryFileSystem inMemoryFileSystem = new();
        TestingPlatformEntryPointTask testingPlatformEntryPoint = new(inMemoryFileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformEntryPointSourcePath = new CustomTaskItem(sourcePath),
            Language = new CustomTaskItem(language),
            RootNamespace = "SomeNamespace",
            HostFactory = "Contoso.Tests.TestHost.CreateHost",
        };

        Assert.IsTrue(testingPlatformEntryPoint.Execute());

        string generatedSource = inMemoryFileSystem.Files[sourcePath]!;
        Assert.Contains(expectedFactoryCall, generatedSource);
        Assert.Contains("RunTestingPlatformAsync", generatedSource);
        Assert.Contains("ShouldBypassApplicationHost", generatedSource);
        Assert.Contains("IAsyncDisposable", generatedSource);
        Assert.Contains("Host disposal failed while handling another exception.", generatedSource);
        Assert.AreEqual(1, CountOccurrences(generatedSource, "SelfRegisteredExtensions.AddSelfRegisteredExtensions(builder, args)"));
        Assert.IsEmpty(_errors);
    }

    [DataRow("CreateHost")]
    [DataRow("Contoso.1Foo.CreateHost")]
    [DataRow("Contoso..CreateHost")]
    [TestMethod]
    public void EntryPointTask_Rejects_Invalid_Host_Factory(string hostFactory)
    {
        InMemoryFileSystem inMemoryFileSystem = new();
        TestingPlatformEntryPointTask testingPlatformEntryPoint = new(inMemoryFileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformEntryPointSourcePath = new CustomTaskItem("obj/applicationHelperFile.cs"),
            Language = new CustomTaskItem("C#"),
            HostFactory = hostFactory,
        };

        Assert.IsFalse(testingPlatformEntryPoint.Execute());

        Assert.IsFalse(inMemoryFileSystem.Files.ContainsKey("obj/applicationHelperFile.cs"));
        Assert.Contains("fully qualified static method path", Assert.ContainsSingle(_errors).Message ?? string.Empty);
    }

    [TestMethod]
    [DataRow("C#", null, null, true, "obj/entryPoint.cs")]
    [DataRow("C#", null, null, false, "obj/application.no-root.cs")]
    [DataRow("C#", "SomeNamespace", null, true, "obj/entryPoint.root.cs")]
    [DataRow("C#", "SomeNamespace", null, false, "obj/application.cs")]
    [DataRow("C#", null, "Contoso.Tests.TestHost.CreateHost", true, "obj/hostedEntryPoint.cs")]
    [DataRow("C#", null, "Contoso.Tests.TestHost.CreateHost", false, "obj/hostedApplication.no-root.cs")]
    [DataRow("C#", "SomeNamespace", "Contoso.Tests.TestHost.CreateHost", true, "obj/hostedEntryPoint.root.cs")]
    [DataRow("C#", "SomeNamespace", "Contoso.Tests.TestHost.CreateHost", false, "obj/hostedApplication.cs")]
    [DataRow("VB", null, null, true, "obj/entryPoint.vb")]
    [DataRow("VB", null, null, false, "obj/application.vb")]
    [DataRow("VB", "Ignored.Root", "Contoso.Tests.TestHost.CreateHost", true, "obj/hostedEntryPoint.vb")]
    [DataRow("VB", "Ignored.Root", "Contoso.Tests.TestHost.CreateHost", false, "obj/hostedApplication.vb")]
    [DataRow("F#", null, null, true, "obj/entryPoint.fs")]
    [DataRow("F#", null, null, false, "obj/application.fs")]
    [DataRow("F#", "SomeNamespace", null, true, "obj/entryPoint.root.fs")]
    [DataRow("F#", "SomeNamespace", null, false, "obj/application.root.fs")]
    [DataRow("F#", null, "Contoso.Tests.TestHost.CreateHost", true, "obj/hostedEntryPoint.no-root.fs")]
    [DataRow("F#", null, "Contoso.Tests.TestHost.CreateHost", false, "obj/hostedApplication.no-root.fs")]
    [DataRow("F#", "SomeNamespace", "Contoso.Tests.TestHost.CreateHost", true, "obj/hostedEntryPoint.fs")]
    [DataRow("F#", "SomeNamespace", "Contoso.Tests.TestHost.CreateHost", false, "obj/hostedApplication.fs")]
    public void EntryPointTask_GeneratesEveryTemplateBranch(
        string language,
        string? rootNamespace,
        string? hostFactory,
        bool generateEntryPoint,
        string sourcePath)
    {
        InMemoryFileSystem fileSystem = new();
        TestingPlatformEntryPointTask task = new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformEntryPointSourcePath = new CustomTaskItem(sourcePath),
            Language = new CustomTaskItem(language),
            RootNamespace = rootNamespace,
            HostFactory = hostFactory,
            GenerateEntryPoint = generateEntryPoint,
        };

        Assert.IsTrue(task.Execute());

        string generatedSource = fileSystem.Files[sourcePath]!;
        Assert.AreEqual(generateEntryPoint, generatedSource.Contains("MicrosoftTestingPlatformEntryPoint", StringComparison.Ordinal));
        Assert.AreEqual(hostFactory is not null, generatedSource.Contains("RunTestingPlatformAsync", StringComparison.Ordinal));
        Assert.DoesNotContain("Stryker was here!", generatedSource);

        if (language == "C#")
        {
            if (rootNamespace is null)
            {
                Assert.DoesNotContain("namespace ", generatedSource);
                Assert.Contains("global::SelfRegisteredExtensions.AddSelfRegisteredExtensions", generatedSource);
            }
            else
            {
                Assert.Contains($"namespace {rootNamespace}", generatedSource);
                Assert.Contains($"global::{rootNamespace}.SelfRegisteredExtensions.AddSelfRegisteredExtensions", generatedSource);
            }
        }
        else if (language == "VB")
        {
            Assert.DoesNotContain("Ignored.Root", generatedSource);
            Assert.Contains("SelfRegisteredExtensions.AddSelfRegisteredExtensions", generatedSource);
        }
        else if (rootNamespace is null)
        {
            Assert.AreEqual(
                !generateEntryPoint,
                generatedSource.Contains("namespace Microsoft.TestingPlatform", StringComparison.Ordinal));
            Assert.Contains(
                "Microsoft.TestingPlatform.Extensions.SelfRegisteredExtensions.AddSelfRegisteredExtensions",
                generatedSource);
        }
        else
        {
            Assert.Contains($"namespace {rootNamespace}", generatedSource);
            Assert.Contains("SelfRegisteredExtensions.AddSelfRegisteredExtensions", generatedSource);
        }

        Assert.AreEqual(sourcePath, task.TestingPlatformEntryPointGeneratedFilePath!.ItemSpec);
        Assert.Contains(
            message => message.Message == $"TestingPlatformEntryPointSourcePath: '{sourcePath}'",
            _messages);
        Assert.Contains(
            message => message.Message == $"Language: '{language}'",
            _messages);
        Assert.Contains(
            message => message.Message == $"Entrypoint source:\n'{generatedSource}'",
            _messages);
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    public void EntryPointTask_AcceptsMinimalQualifiedHostFactoryAndIdentifierCharacters()
    {
        InMemoryFileSystem fileSystem = new();
        TestingPlatformEntryPointTask task = new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformEntryPointSourcePath = new CustomTaskItem("obj/entryPoint.cs"),
            Language = new CustomTaskItem("C#"),
            HostFactory = "_Host1.Create2",
        };

        Assert.IsTrue(task.Execute());
        Assert.Contains(
            "global::_Host1.Create2()",
            fileSystem.Files["obj/entryPoint.cs"]!);
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    public void EntryPointTask_RejectsInvalidCharactersInsideHostFactoryIdentifiers()
    {
        InMemoryFileSystem fileSystem = new();
        TestingPlatformEntryPointTask task = new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformEntryPointSourcePath = new CustomTaskItem("obj/entryPoint.cs"),
            Language = new CustomTaskItem("C#"),
            HostFactory = "Contoso.Bad-Name.Create",
        };

        Assert.IsFalse(task.Execute());
        Assert.IsFalse(fileSystem.Files.ContainsKey("obj/entryPoint.cs"));
        Assert.Contains("fully qualified static method path", Assert.ContainsSingle(_errors).Message ?? string.Empty);
    }

    [TestMethod]
    [DataRow("C#", "obj/entryPoint.cs")]
    [DataRow("F#", "obj/entryPoint.fs")]
    public void EntryPointTask_SanitizesRootNamespaceForNonVisualBasicLanguages(string language, string sourcePath)
    {
        InMemoryFileSystem fileSystem = new();
        TestingPlatformEntryPointTask task = new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformEntryPointSourcePath = new CustomTaskItem(sourcePath),
            Language = new CustomTaskItem(language),
            RootNamespace = "Some-Namespace",
        };

        Assert.IsTrue(task.Execute());
        Assert.Contains("namespace Some_Namespace", fileSystem.Files[sourcePath]!);
        Assert.DoesNotContain("namespace Some-Namespace", fileSystem.Files[sourcePath]!);
    }

    [TestMethod]
    public void SelfRegisteredExtensions_Deduplicates_Exact_Duplicate_BuilderHooks()
    {
        InMemoryFileSystem inMemoryFileSystem = new();
        TestingPlatformSelfRegisteredExtensions selfRegisteredExtensions = new(inMemoryFileSystem)
        {
            BuildEngine = _buildEngine.Object,
            SelfRegisteredExtensionsSourcePath = new CustomTaskItem("obj/selfRegisteredExtensionsFile"),
            Language = new CustomTaskItem("C#"),
            SelfRegisteredExtensionsBuilderHook =
            [
                new CustomTaskItem("hook").Add("DisplayName", "Hook").Add("TypeFullName", "Contoso.Hook"),
                new CustomTaskItem("hook").Add("DisplayName", "Hook").Add("TypeFullName", "Contoso.Hook"),
            ],
        };

        Assert.IsTrue(selfRegisteredExtensions.Execute());

        string generatedSource = inMemoryFileSystem.Files["obj/selfRegisteredExtensionsFile"]!;
        const string ExpectedHookCall = "global::Contoso.Hook.AddExtensions";
        int occurrences = (generatedSource.Length - generatedSource.Replace(ExpectedHookCall, string.Empty).Length) / ExpectedHookCall.Length;
        Assert.AreEqual(1, occurrences);
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    public void SelfRegisteredExtensions_Fails_For_Duplicate_BuilderHook_Ids_With_Different_Metadata()
    {
        InMemoryFileSystem inMemoryFileSystem = new();
        TestingPlatformSelfRegisteredExtensions selfRegisteredExtensions = new(inMemoryFileSystem)
        {
            BuildEngine = _buildEngine.Object,
            SelfRegisteredExtensionsSourcePath = new CustomTaskItem("obj/selfRegisteredExtensionsFile"),
            Language = new CustomTaskItem("C#"),
            SelfRegisteredExtensionsBuilderHook =
            [
                new CustomTaskItem("hook").Add("DisplayName", "Hook").Add("TypeFullName", "Contoso.Hook"),
                new CustomTaskItem("hook").Add("DisplayName", "OtherHook").Add("TypeFullName", "Contoso.OtherHook"),
            ],
        };

        Assert.IsFalse(selfRegisteredExtensions.Execute());

        Assert.IsFalse(inMemoryFileSystem.Files.ContainsKey("obj/selfRegisteredExtensionsFile"));
        Assert.HasCount(1, _errors);
        Assert.Contains("Duplicate 'TestingPlatformBuilderHook' item with Include 'hook' has conflicting metadata.", _errors[0].Message ?? string.Empty);
    }

    [TestMethod]
    [DataRow("DisplayName", "OtherHook")]
    [DataRow("TypeFullName", "Contoso.OtherHook")]
    public void SelfRegisteredExtensions_Fails_WhenOneDuplicateMetadataValueDiffers(string metadataName, string metadataValue)
    {
        InMemoryFileSystem fileSystem = new();
        CustomTaskItem duplicate = new CustomTaskItem("hook")
            .Add("DisplayName", "Hook")
            .Add("TypeFullName", "Contoso.Hook")
            .Add(metadataName, metadataValue);
        TestingPlatformSelfRegisteredExtensions task = new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            SelfRegisteredExtensionsSourcePath = new CustomTaskItem("obj/extensions.cs"),
            Language = new CustomTaskItem("C#"),
            SelfRegisteredExtensionsBuilderHook =
            [
                new CustomTaskItem("hook").Add("DisplayName", "Hook").Add("TypeFullName", "Contoso.Hook"),
                duplicate,
            ],
        };

        Assert.IsFalse(task.Execute());
        Assert.Contains("conflicting metadata", Assert.ContainsSingle(_errors).Message ?? string.Empty);
        Assert.IsFalse(fileSystem.Files.ContainsKey("obj/extensions.cs"));
    }

    [TestMethod]
    [DataRow("C#", null, "obj/extensions.cs", "global::Contoso.First.AddExtensions(builder, args);\n        global::Contoso.Second.AddExtensions(builder, args);")]
    [DataRow("C#", "SomeNamespace", "obj/extensions.root.cs", "global::Contoso.First.AddExtensions(builder, args);\n        global::Contoso.Second.AddExtensions(builder, args);")]
    [DataRow("VB", "Ignored.Root", "obj/extensions.vb", "Global.Contoso.First.AddExtensions(builder, args)\n        Global.Contoso.Second.AddExtensions(builder, args)")]
    [DataRow("F#", null, "obj/extensions.fs", "global.Contoso.First.AddExtensions(builder, args)\n        global.Contoso.Second.AddExtensions(builder, args)")]
    [DataRow("F#", "SomeNamespace", "obj/extensions.root.fs", "global.Contoso.First.AddExtensions(builder, args)\n        global.Contoso.Second.AddExtensions(builder, args)")]
    public void SelfRegisteredExtensions_GeneratesEveryLanguageAndNamespaceBranch(
        string language,
        string? rootNamespace,
        string sourcePath,
        string expectedCalls)
    {
        InMemoryFileSystem fileSystem = new();
        TestingPlatformSelfRegisteredExtensions task = new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            SelfRegisteredExtensionsSourcePath = new CustomTaskItem(sourcePath),
            Language = new CustomTaskItem(language),
            RootNamespace = rootNamespace,
            SelfRegisteredExtensionsBuilderHook =
            [
                new CustomTaskItem("first").Add("DisplayName", "First").Add("TypeFullName", "Contoso.First"),
                new CustomTaskItem("second").Add("DisplayName", "Second").Add("TypeFullName", "Contoso.Second"),
            ],
        };

        Assert.IsTrue(task.Execute());

        string generatedSource = fileSystem.Files[sourcePath]!;
        string normalizedSource = generatedSource.ReplaceLineEndings("\n");
        Assert.Contains(expectedCalls, normalizedSource);
        string lastCall = expectedCalls[(expectedCalls.LastIndexOf('\n') + 1)..];
        Assert.DoesNotContain(lastCall + "\n\n", normalizedSource);
        Assert.DoesNotContain("Stryker was here!", generatedSource);
        if (language == "C#" && rootNamespace is not null)
        {
            Assert.Contains($"namespace {rootNamespace}", generatedSource);
        }
        else if (language == "C#")
        {
            Assert.DoesNotContain($"namespace {Environment.NewLine}{{", generatedSource);
        }
        else if (language == "F#" && rootNamespace is not null)
        {
            Assert.Contains($"namespace {rootNamespace}", generatedSource);
        }
        else if (language == "F#")
        {
            Assert.Contains("namespace Microsoft.TestingPlatform.Extensions", generatedSource);
        }
        else
        {
            Assert.DoesNotContain("Ignored.Root", generatedSource);
        }

        Assert.Contains(
            message => message.Message == $"SelfRegisteredExtensionsSourcePath: '{sourcePath}'",
            _messages);
        Assert.Contains(
            message => message.Message == $"Language: '{language}'",
            _messages);
        Assert.Contains(
            message => message.Message == "TestingPlatformExtensionFullTypeNames:"
                + Environment.NewLine
                + " Hook UID: 'first' DisplayName: 'First' TypeFullName: 'Contoso.First'"
                + Environment.NewLine
                + " Hook UID: 'second' DisplayName: 'Second' TypeFullName: 'Contoso.Second'"
                + Environment.NewLine,
            _messages);
        Assert.Contains(
            message => message.Message == $"SelfRegisteredExtensions source:\n'{generatedSource}'",
            _messages);
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    [DataRow(null)]
    [DataRow("SomeNamespace")]
    public void SelfRegisteredExtensions_FSharpWithoutHooks_EmitsUnitExpression(string? rootNamespace)
    {
        InMemoryFileSystem fileSystem = new();
        TestingPlatformSelfRegisteredExtensions task = new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            SelfRegisteredExtensionsSourcePath = new CustomTaskItem("obj/extensions.fs"),
            Language = new CustomTaskItem("F#"),
            RootNamespace = rootNamespace,
            SelfRegisteredExtensionsBuilderHook = [],
        };

        Assert.IsTrue(task.Execute());
        Assert.Contains(
            "static member AddSelfRegisteredExtensions (builder: Microsoft.Testing.Platform.Builder.ITestApplicationBuilder, args: string[]) =\n        ()",
            fileSystem.Files["obj/extensions.fs"]!.ReplaceLineEndings("\n"));
        Assert.DoesNotContain(
            message => message.Message is not null && message.Message.StartsWith("TestingPlatformExtensionFullTypeNames:", StringComparison.Ordinal),
            _messages);
    }

    [TestMethod]
    [DataRow("C#")]
    [DataRow("F#")]
    public void SelfRegisteredExtensions_SanitizesRootNamespaceForNonVisualBasicLanguages(string language)
    {
        string sourcePath = language == "C#" ? "obj/extensions.cs" : "obj/extensions.fs";
        InMemoryFileSystem fileSystem = new();
        TestingPlatformSelfRegisteredExtensions task = new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            SelfRegisteredExtensionsSourcePath = new CustomTaskItem(sourcePath),
            Language = new CustomTaskItem(language),
            RootNamespace = "Some-Namespace",
            SelfRegisteredExtensionsBuilderHook = [],
        };

        Assert.IsTrue(task.Execute());
        Assert.Contains("namespace Some_Namespace", fileSystem.Files[sourcePath]!);
        Assert.DoesNotContain("namespace Some-Namespace", fileSystem.Files[sourcePath]!);
    }

    [TestMethod]
    public void SelfRegisteredExtensions_StopsAfterFirstConflictingDuplicate()
    {
        InMemoryFileSystem fileSystem = new();
        TestingPlatformSelfRegisteredExtensions task = new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            SelfRegisteredExtensionsSourcePath = new CustomTaskItem("obj/extensions.cs"),
            Language = new CustomTaskItem("C#"),
            SelfRegisteredExtensionsBuilderHook =
            [
                new CustomTaskItem("hook").Add("DisplayName", "First").Add("TypeFullName", "Contoso.First"),
                new CustomTaskItem("hook").Add("DisplayName", "Second").Add("TypeFullName", "Contoso.First"),
                new CustomTaskItem("hook").Add("DisplayName", "Third").Add("TypeFullName", "Contoso.Third"),
            ],
        };

        Assert.IsFalse(task.Execute());
        Assert.HasCount(1, _errors);
    }

    [TestMethod]
    [DataRow("DisplayName")]
    [DataRow("TypeFullName")]
    public void SelfRegisteredExtensions_MissingMetadata_ReportsExpectedItemSpec(string missingMetadata)
    {
        InMemoryFileSystem fileSystem = new();
        CustomTaskItem hook = new("hook");
        if (missingMetadata != "DisplayName")
        {
            hook.Add("DisplayName", "Hook");
        }

        if (missingMetadata != "TypeFullName")
        {
            hook.Add("TypeFullName", "Contoso.Hook");
        }

        TestingPlatformSelfRegisteredExtensions task = new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            SelfRegisteredExtensionsSourcePath = new CustomTaskItem("obj/extensions.cs"),
            Language = new CustomTaskItem("C#"),
            SelfRegisteredExtensionsBuilderHook = [hook],
        };

        Assert.IsFalse(task.Execute());
        string error = Assert.ContainsSingle(_errors).Message ?? string.Empty;
        Assert.Contains($"Missing '{missingMetadata}' metadata", error);
        Assert.Contains("<TestingPlatformBuilderHook Include=\"8E680F4D-E423-415A-9566-855439363BC0\" >", error);
        Assert.Contains("static Contoso.BuilderHook.AddExtensions", error);
    }

    [TestMethod]
    public void ConfigurationFileTask_MergesOptionDefaultsAndPreservesJsonOverrides()
    {
        string projectDirectory = Path.Combine("root", "project");
        string sourcePath = Path.Combine(projectDirectory, "testconfig.json");
        string outputPath = Path.Combine(projectDirectory, "bin", "Tests.testconfig.json");
        InMemoryFileSystem fileSystem = new();
        fileSystem.Files[sourcePath] =
            """
            {
              "platformOptions": {
                "exitProcessOnUnhandledException": true
              },
              "commandLineOptionDefaults": {
                "report-trx-filename": "from-json.trx"
              }
            }
            """;
        ConfigurationFileTask task = CreateConfigurationFileTask(fileSystem, projectDirectory);
        task.TestingPlatformCommandLineOptionDefault =
        [
            new CustomTaskItem("report-trx-filename").Add("Value", "from-msbuild.trx"),
            new CustomTaskItem("filter-uid").Add("Value", "first"),
            new CustomTaskItem("filter-uid").Add("Value", "second"),
        ];

        Assert.IsTrue(task.Execute());

        string? output = fileSystem.Files[outputPath];
        Assert.IsNotNull(output);
        using var document = JsonDocument.Parse(output);
        JsonElement root = document.RootElement;
        Assert.IsTrue(root.GetProperty("platformOptions").GetProperty("exitProcessOnUnhandledException").GetBoolean());
        JsonElement defaults = root.GetProperty("commandLineOptionDefaults");
        Assert.AreEqual("from-json.trx", defaults.GetProperty("report-trx-filename").GetString());
        Assert.AreSequenceEqual(
            ["first", "second"],
            defaults.GetProperty("filter-uid").EnumerateArray().Select(x => x.GetString()).ToArray());
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    public void ConfigurationFileTask_GeneratesConfigurationFromOptionDefaults()
    {
        string projectDirectory = Path.Combine("root", "project");
        string outputPath = Path.Combine(projectDirectory, "bin", "Tests.testconfig.json");
        InMemoryFileSystem fileSystem = new();
        ConfigurationFileTask task = CreateConfigurationFileTask(fileSystem, projectDirectory);
        task.TestingPlatformCommandLineOptionDefault =
        [
            new CustomTaskItem("report-trx-filename").Add("Value", "{asm}.trx"),
        ];

        Assert.IsTrue(task.Execute());

        string? output = fileSystem.Files[outputPath];
        Assert.IsNotNull(output);
        using var document = JsonDocument.Parse(output);
        Assert.AreEqual(
            "{asm}.trx",
            document.RootElement.GetProperty("commandLineOptionDefaults").GetProperty("report-trx-filename").GetString());
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    public void ConfigurationFileTask_RejectsOptionNameWithLeadingHyphens()
    {
        InMemoryFileSystem fileSystem = new();
        ConfigurationFileTask task = CreateConfigurationFileTask(fileSystem, Path.Combine("root", "project"));
        task.TestingPlatformCommandLineOptionDefault =
        [
            new CustomTaskItem("--report-trx-filename").Add("Value", "{asm}.trx"),
        ];

        Assert.IsFalse(task.Execute());
        Assert.Contains("without leading hyphens", Assert.ContainsSingle(_errors).Message ?? string.Empty);
    }

    [TestMethod]
    public void ConfigurationFileTask_ReportsDuplicateJsonKeys()
    {
        string projectDirectory = Path.Combine("root", "project");
        string sourcePath = Path.Combine(projectDirectory, "testconfig.json");
        string outputPath = Path.Combine(projectDirectory, "bin", "Tests.testconfig.json");
        InMemoryFileSystem fileSystem = new();
        fileSystem.Files[sourcePath] =
            """
            {
              "commandLineOptionDefaults": {},
              "commandLineOptionDefaults": {}
            }
            """;
        ConfigurationFileTask task = CreateConfigurationFileTask(fileSystem, projectDirectory);
        task.TestingPlatformCommandLineOptionDefault =
        [
            new CustomTaskItem("report-trx-filename").Add("Value", "{asm}.trx"),
        ];

        Assert.IsFalse(task.Execute());
        Assert.Contains("duplicate keys", Assert.ContainsSingle(_errors).Message ?? string.Empty, StringComparison.OrdinalIgnoreCase);
        Assert.IsFalse(fileSystem.Files.ContainsKey(outputPath));
    }

    [TestMethod]
    public void ConfigurationFileTask_MissingSourceAndDefaults_ProducesNoOutputAndExactDiagnostics()
    {
        string projectDirectory = Path.Combine("root", "project");
        InMemoryFileSystem fileSystem = new();
        ConfigurationFileTask task = CreateConfigurationFileTask(fileSystem, projectDirectory);

        Assert.IsTrue(task.Execute());
        Assert.IsNull(task.FinalTestingPlatformConfigurationFile);
        Assert.AreSequenceEqual(
            [
                $"Microsoft Testing Platform configuration file: '{Path.Combine(projectDirectory, "testconfig.json")}'",
                "Microsoft Testing Platform configuration file not found",
            ],
            _messages.Select(message => message.Message).ToArray());
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    public void ConfigurationFileTask_MissingSourceAndEmptyDefaults_ProducesNoOutput()
    {
        string projectDirectory = Path.Combine("root", "project");
        InMemoryFileSystem fileSystem = new();
        ConfigurationFileTask task = CreateConfigurationFileTask(fileSystem, projectDirectory);
        task.TestingPlatformCommandLineOptionDefault = [];

        Assert.IsTrue(task.Execute());
        Assert.IsNull(task.FinalTestingPlatformConfigurationFile);
        Assert.AreEqual(
            "Microsoft Testing Platform configuration file not found",
            _messages[^1].Message);
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    [ResourceLock(WellKnownResources.EnvironmentVariables)]
    public void EmbeddedRuntimeDefaults_AreInitializedInFreshAssembly()
    {
        const string TimeoutEnvironmentVariable = "TESTINGPLATFORM_DEFAULT_HANG_TIMEOUT";
        string? originalTimeout = Environment.GetEnvironmentVariable(TimeoutEnvironmentVariable);
        Environment.SetEnvironmentVariable(TimeoutEnvironmentVariable, null);
        var loadContext = new IsolatedAssemblyLoadContext();
        try
        {
            Assembly assembly = loadContext.LoadFromAssemblyPath(typeof(ConfigurationFileTask).Assembly.Location);

            Type timeoutHelper = assembly.GetType("Microsoft.Testing.Platform.Helpers.TimeoutHelper", throwOnError: true)!;
            Assert.AreEqual(
                TimeSpan.FromMinutes(5),
                timeoutHelper.GetProperty("DefaultHangTimeSpanTimeout", BindingFlags.Static | BindingFlags.Public)!.GetValue(null));
            Assert.AreEqual(
                300d,
                timeoutHelper.GetProperty("DefaultHangTimeoutSeconds", BindingFlags.Static | BindingFlags.Public)!.GetValue(null));

            Type invokeTask = assembly.GetType("Microsoft.Testing.Platform.MSBuild.InvokeTestingPlatformTask", throwOnError: true)!;
            Assert.AreEqual(
                RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "dotnet.exe" : "dotnet",
                invokeTask.GetField("DotnetRunnerName", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null));
        }
        finally
        {
            loadContext.Unload();
            Environment.SetEnvironmentVariable(TimeoutEnvironmentVariable, originalTimeout);
        }
    }

    [TestMethod]
    public void ConfigurationFileTask_CopiesExistingSourceAndLogsEveryResolvedPath()
    {
        string projectDirectory = Path.Combine("root", "project");
        string sourcePath = Path.Combine(projectDirectory, "testconfig.json");
        string finalPath = Path.Combine(projectDirectory, "bin");
        string outputPath = Path.Combine(finalPath, "Tests.testconfig.json");
        InMemoryFileSystem fileSystem = new();
        fileSystem.Files[sourcePath] = """{"original":true}""";
        ConfigurationFileTask task = CreateConfigurationFileTask(fileSystem, projectDirectory);

        Assert.IsTrue(task.Execute());

        Assert.AreEqual(fileSystem.Files[sourcePath], fileSystem.Files[outputPath]);
        Assert.AreEqual(outputPath, task.FinalTestingPlatformConfigurationFile!.ItemSpec);
        Assert.AreSequenceEqual(
            [
                $"Microsoft Testing Platform configuration file: '{sourcePath}'",
                $"MSBuildProjectDirectory: '{projectDirectory}'",
                "AssemblyName: 'Tests'",
                "OutputPath: 'bin'",
                $"Final path: '{finalPath}'",
                $"Final configuration file path : '{outputPath}'",
                $"Configuration file found: '{sourcePath}'",
                "Microsoft Testing Platform configuration file written",
            ],
            _messages.Select(message => message.Message).ToArray());
        Assert.IsEmpty(_errors);
    }

    [TestMethod]
    public void ConfigurationFileTask_AllowsCommentsAndTrailingCommasAndWritesIndentedJson()
    {
        string projectDirectory = Path.Combine("root", "project");
        string sourcePath = Path.Combine(projectDirectory, "testconfig.json");
        string outputPath = Path.Combine(projectDirectory, "bin", "Tests.testconfig.json");
        InMemoryFileSystem fileSystem = new();
        fileSystem.Files[sourcePath] =
            """
            {
              // Preserve comments while parsing, but normalize them out of the generated file.
              "platformOptions": {
                "exitProcessOnUnhandledException": true,
              },
            }
            """;
        ConfigurationFileTask task = CreateConfigurationFileTask(fileSystem, projectDirectory);
        task.TestingPlatformCommandLineOptionDefault =
        [
            new CustomTaskItem("filter-uid").Add("Value", "first"),
            new CustomTaskItem("filter-uid").Add("Value", "second"),
        ];

        Assert.IsTrue(task.Execute());

        string output = fileSystem.Files[outputPath]!;
        Assert.Contains(Environment.NewLine + "  \"platformOptions\": {", output);
        Assert.Contains(Environment.NewLine + "    \"exitProcessOnUnhandledException\": true", output);
        Assert.Contains(Environment.NewLine + "  \"commandLineOptionDefaults\": {", output);
        Assert.Contains(Environment.NewLine + "    \"filter-uid\": [", output);
        Assert.EndsWith(Environment.NewLine, output);
        Assert.DoesNotContain("// Preserve comments", output);
        Assert.IsEmpty(_errors);
    }

    private ConfigurationFileTask CreateConfigurationFileTask(InMemoryFileSystem fileSystem, string projectDirectory)
        => new(fileSystem)
        {
            BuildEngine = _buildEngine.Object,
            TestingPlatformConfigurationFileSource = new CustomTaskItem(Path.Combine(projectDirectory, "testconfig.json")),
            MSBuildProjectDirectory = new CustomTaskItem(projectDirectory),
            AssemblyName = new CustomTaskItem("Tests"),
            OutputPath = new CustomTaskItem("bin"),
        };

    private static int CountOccurrences(string value, string fragment)
        => (value.Length - value.Replace(fragment, string.Empty).Length) / fragment.Length;

    private sealed class InMemoryFileSystem : IFileSystem
    {
        public Dictionary<string, string?> Files { get; } = [];

        public void CopyFile(string source, string destination) => Files[destination] = Files[source];

        public void CreateDirectory(string directory)
        {
        }

        public Stream CreateNew(string path) => throw new NotImplementedException();

        public bool Exist(string path) => Files.ContainsKey(path);

        public string ReadAllText(string path) => Files[path]!;

        public void WriteAllText(string path, string? contents) => Files[path] = contents;
    }

    private sealed class CustomTaskItem : ITaskItem
    {
        private readonly Dictionary<string, string> _keyValuePairs = [];

        public CustomTaskItem(string itemSpec) => ItemSpec = itemSpec;

        public CustomTaskItem Add(string key, string value)
        {
            _keyValuePairs[key] = value;
            return this;
        }

        public string ItemSpec { get; set; }

        public ICollection MetadataNames => throw new NotImplementedException();

        public int MetadataCount => _keyValuePairs.Count;

        public IDictionary CloneCustomMetadata() => throw new NotImplementedException();

        public void CopyMetadataTo(ITaskItem destinationItem) => throw new NotImplementedException();

        public string? GetMetadata(string metadataName) => _keyValuePairs.TryGetValue(metadataName, out string? value) ? value : null;

        public void RemoveMetadata(string metadataName) => throw new NotImplementedException();

        public void SetMetadata(string metadataName, string metadataValue) => throw new NotImplementedException();
    }

    private sealed class IsolatedAssemblyLoadContext : AssemblyLoadContext
    {
        public IsolatedAssemblyLoadContext()
            : base(isCollectible: true)
        {
        }

        protected override Assembly? Load(AssemblyName assemblyName)
            => Default.Assemblies.FirstOrDefault(
                assembly => AssemblyName.ReferenceMatchesDefinition(assembly.GetName(), assemblyName));
    }
}
