using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace UnskipClosedTests.Tool;

internal static partial class InventoryEngine
{
    private static List<ParsedFile> LoadFiles(GitRepository repository, ToolConfig config)
    {
        Dictionary<string, string> paths = new(StringComparer.Ordinal);
        foreach (string configuredRoot in config.SourceRoots)
        {
            string normalizedRoot = PathRules.ValidateRelativePath(configuredRoot, "source root");
            string fullRoot = PathRules.ResolveInsideRoot(repository.Root, normalizedRoot, "source root");
            if (File.Exists(fullRoot))
            {
                if (!normalizedRoot.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
                {
                    throw new ContractException($"Source root '{normalizedRoot}' is not a C# file.");
                }

                if (PathRules.MatchesAnyGlob(normalizedRoot, config.ExcludedGlobs.Concat(config.GeneratedGlobs)))
                {
                    throw new ContractException($"Explicit source root '{normalizedRoot}' is excluded or generated.");
                }

                paths[normalizedRoot] = fullRoot;
                continue;
            }

            if (!Directory.Exists(fullRoot))
            {
                continue;
            }

            PathRules.RejectReparsePoints(repository.Root, fullRoot);
            foreach (string file in Directory.EnumerateFiles(fullRoot, "*", SearchOption.AllDirectories))
            {
                string extension = Path.GetExtension(file);
                if (!string.Equals(extension, ".cs", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                string relative = Path.GetRelativePath(repository.Root, file).Replace('\\', '/');
                relative = PathRules.ValidateRelativePath(relative, "source path");
                if (PathRules.MatchesAnyGlob(relative, config.ExcludedGlobs.Concat(config.GeneratedGlobs)))
                {
                    continue;
                }

                paths[relative] = file;
            }
        }

        List<ParsedFile> result = [];
        foreach ((string relative, string fullPath) in paths.OrderBy(static pair => pair.Key, StringComparer.Ordinal))
        {
            PathRules.RejectReparsePoints(repository.Root, fullPath);
            byte[] bytes;
            try
            {
                bytes = File.ReadAllBytes(fullPath);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                throw new InfrastructureException($"Could not read source path '{relative}'.", ex);
            }

            string blobOid = repository.HeadBlobOid(relative);
            repository.RequireWorktreeMatchesHead(relative, bytes);
            string source;
            try
            {
                int offset = bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF ? 3 : 0;
                source = new UTF8Encoding(false, true).GetString(bytes, offset, bytes.Length - offset);
            }
            catch (DecoderFallbackException ex)
            {
                throw new ContractException($"Source path '{relative}' is not valid UTF-8: {ex.Message}");
            }

            string prefix = source[..Math.Min(source.Length, 2048)];
            if (prefix.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase) ||
                prefix.Contains("<autogenerated", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            SyntaxTree tree = CSharpSyntaxTree.ParseText(
                SourceText.From(source, Encoding.UTF8),
                new CSharpParseOptions(LanguageVersion.Latest, DocumentationMode.Parse),
                relative);
            List<Diagnostic> errors = tree.GetDiagnostics()
                .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
                .ToList();
            if (errors.Count > 0)
            {
                throw new ContractException(
                    $"Source path '{relative}' has C# parse errors: {string.Join("; ", errors.Take(3))}");
            }

            result.Add(new ParsedFile(relative, fullPath, bytes, blobOid, tree, tree.GetCompilationUnitRoot()));
        }

        return result;
    }

    private static Dictionary<string, int> CountTypeDeclarations(IEnumerable<ParsedFile> files)
    {
        Dictionary<string, int> counts = new(StringComparer.Ordinal);
        foreach (TypeDeclarationSyntax declaration in files.SelectMany(static file =>
                     file.Root.DescendantNodes().OfType<TypeDeclarationSyntax>()))
        {
            string fqn = TypeFqn(declaration);
            counts[fqn] = counts.GetValueOrDefault(fqn) + 1;
        }

        return counts;
    }
}
