//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyVersionAttribute("14.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("14.0.0.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("14.0.0.1")]
[assembly: System.Reflection.AssemblyVersionAttribute("14.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("14.0.0.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("14.0.0.1")]

// Generated by the MSBuild WriteCodeFragment class.

