<Project>

  <PropertyGroup>
    <AspireTestingVersion>13.4.6</AspireTestingVersion>
    <CodeCoverageVersion>18.12.0-preview.26479.4</CodeCoverageVersion>
    <MSTestVersion>4.5.0-preview.26480.9</MSTestVersion>
    <MSTestExtensionsHostingVersion Condition="'$(MSTestExtensionsHostingVersion)' == ''">4.5.0-preview.26480.9</MSTestExtensionsHostingVersion>
    <MTPVersion>2.5.0-preview.26480.9</MTPVersion>
    <MicrosoftTestingExtensionsHostingVersion Condition="'$(MicrosoftTestingExtensionsHostingVersion)' == ''">$([System.String]::Copy('$(MTPVersion)').Replace('2.5.0-preview.', '1.0.0-alpha.'))</MicrosoftTestingExtensionsHostingVersion>
    <PlaywrightVersion>1.61.0</PlaywrightVersion>
    <VSTestVersion>18.10.1</VSTestVersion>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);SA0001;EnableGenerateDocumentationFile</NoWarn>
  </PropertyGroup>

</Project>
