<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <DefaultLanguage>en-US</DefaultLanguage>
    <PublishAot>true</PublishAot>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    <UseUwp>true</UseUwp>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <EnableMsixTooling>true</EnableMsixTooling>
    <EnableMicrosoftTestingExtensionsPackagedApp Condition="'$(EnableMicrosoftTestingExtensionsPackagedApp)' == ''">false</EnableMicrosoftTestingExtensionsPackagedApp>
    <DefineConstants Condition="'$(EnableMicrosoftTestingExtensionsPackagedApp)' == 'true'">$(DefineConstants);PACKAGED_APP_TESTING</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Remove="MainPage.xaml" />
    <ApplicationDefinition Include="App.xaml"
                           Condition="'$(EnableMicrosoftTestingExtensionsPackagedApp)' == 'true'" />
    <Page Include="MainPage.xaml"
          Condition="'$(EnableMicrosoftTestingExtensionsPackagedApp)' == 'true'" />
  </ItemGroup>
</Project>
