<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<NoWarn>$(NoWarn);MSTEST0032</NoWarn>

		<OutputType>Exe</OutputType>
		<EnableMSTestRunner>true</EnableMSTestRunner>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest" Version="$(MSTestVersion)" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="$(MTPVersion)" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="$(CodeCoverageVersion)" />
	</ItemGroup>

</Project>
