<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="$(AspireVersion)" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <NoWarn>$(NoWarn);ASPIRE010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="$(AspireVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireApi\AspireApi.csproj" />
  </ItemGroup>

</Project>
