// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Microsoft.Testing.Platform.MSBuild;

public sealed partial class TestingPlatformEntryPointTask
{
    private static string GetVisualBasicEntryPointSourceCode(bool generateEntryPoint) => $$"""
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by Microsoft.Testing.Platform.MSBuild
' </auto-generated>
'------------------------------------------------------------------------------

<System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>
Friend Module MicrosoftTestingPlatformApplication
    Public Async Function RunAsync(args As String()) As Global.System.Threading.Tasks.Task(Of Integer)
        Dim builder = Await Global.Microsoft.Testing.Platform.Builder.TestApplication.CreateBuilderAsync(args)
        SelfRegisteredExtensions.AddSelfRegisteredExtensions(builder, args)
        Using testApplication = Await builder.BuildAsync()
            Return Await testApplication.RunAsync()
        End Using
    End Function

End Module
{{(generateEntryPoint ? """

<System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>
Module MicrosoftTestingPlatformEntryPoint
    Function Main(args As String()) As Integer
        Return MicrosoftTestingPlatformApplication.RunAsync(args).GetAwaiter().GetResult()
    End Function

    Public Function MainAsync(args As String()) As Global.System.Threading.Tasks.Task(Of Integer)
        Return MicrosoftTestingPlatformApplication.RunAsync(args)
    End Function
End Module
""" : string.Empty)}}
""";

    private static string GetHostedVisualBasicEntryPointSourceCode(bool generateEntryPoint, string hostFactory) => $$"""
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by Microsoft.Testing.Platform.MSBuild
' </auto-generated>
'------------------------------------------------------------------------------

<System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>
Friend Module MicrosoftTestingPlatformApplication
    Public Async Function RunAsync(args As String()) As Global.System.Threading.Tasks.Task(Of Integer)
        If Global.Microsoft.Testing.Extensions.MicrosoftExtensionsHostingExtensions.ShouldBypassApplicationHost(args) Then
            Dim builder = Await Global.Microsoft.Testing.Platform.Builder.TestApplication.CreateBuilderAsync(args)
            AddSelfRegisteredExtensions(builder, args)
            Using testApplication = Await builder.BuildAsync()
                Return Await testApplication.RunAsync()
            End Using
        End If

        Dim host As Global.Microsoft.Extensions.Hosting.IHost = Await Global.{{hostFactory}}()
        Dim exitCode As Integer = 0
        Dim runException As Global.System.Exception = Nothing
        Try
            exitCode = Await Global.Microsoft.Testing.Extensions.MicrosoftExtensionsHostingExtensions.RunTestingPlatformAsync(
                host,
                args,
                Sub(builder) AddSelfRegisteredExtensions(builder, args))
        Catch ex As Global.System.Exception
            runException = ex
        End Try

        Await DisposeHostAsync(host, runException)
        If runException IsNot Nothing Then
            Global.System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(runException).Throw()
        End If

        Return exitCode
    End Function

    Private Sub AddSelfRegisteredExtensions(builder As Global.Microsoft.Testing.Platform.Builder.ITestApplicationBuilder, args As String())
        SelfRegisteredExtensions.AddSelfRegisteredExtensions(builder, args)
    End Sub

    Private Async Function DisposeHostAsync(host As Global.Microsoft.Extensions.Hosting.IHost, operationException As Global.System.Exception) As Global.System.Threading.Tasks.Task
        Dim disposeException As Global.System.Exception = Nothing
        Try
            Dim asyncDisposable = TryCast(host, Global.System.IAsyncDisposable)
            If asyncDisposable IsNot Nothing Then
                Await asyncDisposable.DisposeAsync()
            Else
                host.Dispose()
            End If
        Catch ex As Global.System.Exception
            disposeException = ex
        End Try

        If disposeException IsNot Nothing Then
            If operationException IsNot Nothing Then
                Throw New Global.System.AggregateException(
                    "Host disposal failed while handling another exception.",
                    operationException,
                    disposeException)
            End If

            Global.System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(disposeException).Throw()
        End If
    End Function

End Module
{{(generateEntryPoint ? """

<System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>
Module MicrosoftTestingPlatformEntryPoint
    Function Main(args As String()) As Integer
        Return MicrosoftTestingPlatformApplication.RunAsync(args).GetAwaiter().GetResult()
    End Function

    Public Function MainAsync(args As String()) As Global.System.Threading.Tasks.Task(Of Integer)
        Return MicrosoftTestingPlatformApplication.RunAsync(args)
    End Function
End Module
""" : string.Empty)}}
""";
}
