<Project>

  <Target Name="_BuildTestingPlatformMSBuildTaskForHostedSample"
          BeforeTargets="_GetTestingPlatformMSBuildTaskFileHashForEntryPoint;_GetTestingPlatformMSBuildTaskFileHashForSelfRegisteredExtensions"
          Condition=" '$(TestingPlatformHostFactory)' != '' ">
    <MSBuild Projects="$(MSBuildThisFileDirectory)..\..\..\src\Platform\Microsoft.Testing.Platform.MSBuild\Microsoft.Testing.Platform.MSBuild.csproj"
             Targets="Build"
             Properties="Configuration=$(Configuration);TargetFramework=netstandard2.0"
             BuildInParallel="false" />
  </Target>

</Project>
