// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#if !IS_CORE_MTP
using System.Resources;
#endif

using Microsoft.CodeAnalysis;

#if !IS_CORE_MTP
#pragma warning disable IDE0005 // Using directive is unnecessary.
using Microsoft.Testing.Platform.Builder;
#pragma warning restore IDE0005 // Using directive is unnecessary.
#endif

namespace Microsoft.Testing.Platform.OutputDevice.Terminal;

// Strongly-typed accessor for TerminalResources.resx. In core MTP the accessor is generated by Arcade
// (GenerateSource). We add this [Embedded] partial so the type is embedded per-assembly when the terminal
// reporter source is shared with external consumers (e.g. dotnet/sdk's 'dotnet test'). When linked into an
// assembly that does NOT compile the resx (e.g. the unit-test project), the !IS_CORE_MTP block provides a
// ResourceManager pointing at the core MTP assembly, mirroring the PlatformResources pattern.
[Embedded]
internal static partial class TerminalResources
{
#if !IS_CORE_MTP

    internal static ResourceManager ResourceManager => field ??= new ResourceManager("Microsoft.Testing.Platform.OutputDevice.Terminal.TerminalResources", typeof(ITestApplication).Assembly);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static string GetResourceString(string resourceKey) => ResourceManager.GetString(resourceKey, null)!;

    internal static string @Aborted => GetResourceString("Aborted");

    internal static string @Actual => GetResourceString("Actual");

    internal static string @CancelledLowercase => GetResourceString("CancelledLowercase");

    internal static string @CancellingTestSession => GetResourceString("CancellingTestSession");

    internal static string @PressCtrlCAgainToForceExit => GetResourceString("PressCtrlCAgainToForceExit");

    internal static string @Expected => GetResourceString("Expected");

    internal static string @FailedLowercase => GetResourceString("FailedLowercase");

    internal static string @ForTest => GetResourceString("ForTest");

    internal static string @InProcessArtifactsProduced => GetResourceString("InProcessArtifactsProduced");

    internal static string @OutOfProcessArtifactsProduced => GetResourceString("OutOfProcessArtifactsProduced");

    internal static string @PassedLowercase => GetResourceString("PassedLowercase");

    internal static string @SkippedLowercase => GetResourceString("SkippedLowercase");

    internal static string @TotalLowercase => GetResourceString("TotalLowercase");

    internal static string @ConsoleIsAlreadyInBatchingMode => GetResourceString("ConsoleIsAlreadyInBatchingMode");

    internal static string @DurationLowercase => GetResourceString("DurationLowercase");

    internal static string @TestRunSummary => GetResourceString("TestRunSummary");

    internal static string @StackFrameAt => GetResourceString("StackFrameAt");

    internal static string @StackFrameIn => GetResourceString("StackFrameIn");

    internal static string @TerminalNoAnsiOptionDescription => GetResourceString("TerminalNoAnsiOptionDescription");

    internal static string @TerminalAnsiOptionDescription => GetResourceString("TerminalAnsiOptionDescription");

    internal static string @TerminalAnsiOptionInvalidArgument => GetResourceString("TerminalAnsiOptionInvalidArgument");

    internal static string @TerminalNoProgressOptionDescription => GetResourceString("TerminalNoProgressOptionDescription");

    internal static string @TerminalProgressOptionDescription => GetResourceString("TerminalProgressOptionDescription");

    internal static string @TerminalProgressOptionInvalidArgument => GetResourceString("TerminalProgressOptionInvalidArgument");

    internal static string @TerminalProgressHeartbeat => GetResourceString("TerminalProgressHeartbeat");

    internal static string @TerminalProgressHeartbeatActiveSuffix => GetResourceString("TerminalProgressHeartbeatActiveSuffix");

    internal static string @TerminalProgressSlowTest => GetResourceString("TerminalProgressSlowTest");

    internal static string @TerminalTestReporterDescription => GetResourceString("TerminalTestReporterDescription");

    internal static string @TerminalTestReporterDisplayName => GetResourceString("TerminalTestReporterDisplayName");

    internal static string @TerminalOutputOptionDescription => GetResourceString("TerminalOutputOptionDescription");

    internal static string @TerminalOutputOptionInvalidArgument => GetResourceString("TerminalOutputOptionInvalidArgument");

    internal static string @TerminalShowStdoutOptionDescription => GetResourceString("TerminalShowStdoutOptionDescription");

    internal static string @TerminalShowStderrOptionDescription => GetResourceString("TerminalShowStderrOptionDescription");

    internal static string @TerminalShowOutputOptionInvalidArgument => GetResourceString("TerminalShowOutputOptionInvalidArgument");

    internal static string @StandardError => GetResourceString("StandardError");

    internal static string @StandardOutput => GetResourceString("StandardOutput");

    internal static string @TestDiscoverySummarySingular => GetResourceString("TestDiscoverySummarySingular");

    internal static string @ActiveTestsRunning_MoreTestsCount => GetResourceString("ActiveTestsRunning_MoreTestsCount");

    internal static string @ActiveTestsRunning_FullTestsCount => GetResourceString("ActiveTestsRunning_FullTestsCount");

    internal static string @SucceededLowercase => GetResourceString("SucceededLowercase");

#endif
}
