<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net9.0-windows</TargetFrameworks>
    <EnableWindowsTargeting Condition=" '$(OS)' != 'Windows_NT' ">true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WPF" />
  </ItemGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>MSTest.Windows.AppTesting</PackageId>
    <PackageTags>$(CommonPackageTags) Windows AppTesting UIAutomation WinForms WPF E2E EndToEnd</PackageTags>
    <PackageDescription><![CDATA[MSTest base classes for end-to-end testing of Windows desktop applications through Windows UI Automation.

$(CommonProductDescription)]]></PackageDescription>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>Microsoft.MSTest.Windows.AppTesting</RootNamespace>
    <AssemblyName>MSTest.Windows.AppTesting</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src\TestFramework\TestFramework.Extensions\TestFramework.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="PublicAPI\PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI\PublicAPI.Unshipped.txt" />
  </ItemGroup>

</Project>
