// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.SourceGeneration.Helpers;

using Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.SourceGeneration.Models;

namespace Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.SourceGeneration.Generators;

/// <summary>
/// Emits a single <c>[ModuleInitializer]</c> that registers the test assembly with MSTest's
/// adapter via <c>ReflectionMetadataHook.Register</c>. This is what makes a project that
/// references only this generator discoverable and runnable.
/// <para>
/// The initializer <b>consumes the <c>MSTestReflectionMetadata</c> registry</b> emitted by
/// <see cref="MetadataRegistryEmitter"/>: it iterates the registry's test classes and publishes
/// the delegate-based invokers (constructor factories, method invokers, property setters) so the
/// adapter executes tests without runtime reflection (<c>MethodInfo.Invoke</c> /
/// <c>Activator.CreateInstance</c> / <c>PropertyInfo.SetValue</c>). The reflection objects that
/// the adapter still keys on (<see cref="System.Reflection.MethodInfo"/>,
/// <see cref="System.Reflection.PropertyInfo"/>) are resolved once at module-load time under the
/// member-scoped <c>[DynamicDependency]</c> roots emitted below.
/// </para>
/// </summary>
internal static class RuntimeRegistrationEmitter
{
    private const string GeneratedTypeName = "MSTestAotSourceGeneratedReflectionMetadata";
    private const string GeneratedNamespace = "Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.SourceGeneration.Generated.Aot";
    private const string RegistryNamespace = "global::MSTest.SourceGenerated";
    private const string ConstructorInvokerInfoFullName = "global::Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.SourceGeneration.ConstructorInvokerInfo";

    public static string Emit(IReadOnlyList<TestClassModel> testClasses)
    {
        var sb = new IndentedStringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.SourceGeneration. Do not edit.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        using (sb.Block($"namespace {GeneratedNamespace}"))
        {
            using (sb.Block($"internal static class {GeneratedTypeName}"))
            {
                EmitTestClassMemberTypes(sb);
                sb.AppendLine();
                sb.AppendLine("[ModuleInitializer]");
                EmitDynamicDependencies(sb, testClasses);

                using (sb.Block("internal static void Initialize()"))
                {
                    EmitInitializeBody(sb, testClasses);
                }

                sb.AppendLine();
                EmitResolveMethodHelper(sb);
                sb.AppendLine();
                EmitResolvePropertyHelper(sb);
            }
        }

        return sb.ToString();
    }

    private static void EmitTestClassMemberTypes(IndentedStringBuilder sb)
    {
        sb.AppendLine("private const DynamicallyAccessedMemberTypes TestClassMemberTypes =");
        sb.IndentationLevel++;
        sb.AppendLine("DynamicallyAccessedMemberTypes.PublicConstructors |");
        sb.AppendLine("DynamicallyAccessedMemberTypes.NonPublicConstructors |");
        sb.AppendLine("DynamicallyAccessedMemberTypes.PublicMethods |");
        sb.AppendLine("DynamicallyAccessedMemberTypes.NonPublicMethods |");
        sb.AppendLine("DynamicallyAccessedMemberTypes.PublicFields |");
        sb.AppendLine("DynamicallyAccessedMemberTypes.NonPublicFields |");
        sb.AppendLine("DynamicallyAccessedMemberTypes.PublicProperties |");
        sb.AppendLine("DynamicallyAccessedMemberTypes.NonPublicProperties;");
        sb.IndentationLevel--;
    }

    private static void EmitDynamicDependencies(IndentedStringBuilder sb, IReadOnlyList<TestClassModel> testClasses)
    {
        var emittedBases = new HashSet<string>(StringComparer.Ordinal);
        foreach (TestClassModel cls in testClasses)
        {
            sb.AppendLine($"[DynamicDependency(TestClassMemberTypes, typeof({cls.FullyQualifiedTypeName}))]");
        }

        foreach (TestClassModel cls in testClasses)
        {
            foreach (string baseType in cls.BaseTypeFullyQualifiedNames)
            {
                if (emittedBases.Add(baseType))
                {
                    sb.AppendLine($"[DynamicDependency(TestClassMemberTypes, typeof({baseType}))]");
                }
            }
        }

        var emittedEnums = new HashSet<string>(StringComparer.Ordinal);
        foreach (TestClassModel cls in testClasses)
        {
            foreach (TestMethodModel method in cls.Methods)
            {
                foreach (TestParameterModel parameter in method.Parameters)
                {
                    if (parameter.EnumFullyQualifiedType is string enumType && emittedEnums.Add(enumType))
                    {
                        sb.AppendLine($"[DynamicDependency(DynamicallyAccessedMemberTypes.PublicFields, typeof({enumType}))]");
                    }
                }
            }
        }
    }

    private static void EmitInitializeBody(IndentedStringBuilder sb, IReadOnlyList<TestClassModel> testClasses)
    {
        int typeAttributeCount = 0;
        int methodCount = 0;
        int methodAttributeCount = 0;
        int propertySetterCount = 0;

        foreach (TestClassModel testClass in testClasses)
        {
            typeAttributeCount += testClass.AreAttributesComplete ? 1 : 0;
            methodCount += testClass.Methods.Length;
            foreach (TestMethodModel method in testClass.Methods)
            {
                methodAttributeCount += method.AreAttributesComplete ? 1 : 0;
            }

            foreach (TestPropertyModel property in testClass.Properties)
            {
                propertySetterCount += property.HasPublicSetter ? 1 : 0;
            }
        }

        sb.AppendLine($"var assembly = typeof({GeneratedTypeName}).Assembly;");
        sb.AppendLine($"IReadOnlyList<{RegistryNamespace}.TestClassReflectionInfo> testClasses = {RegistryNamespace}.MSTestReflectionMetadata.TestClasses;");
        sb.AppendLine();
        sb.AppendLine("const BindingFlags memberFlags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;");
        sb.AppendLine("var types = new Type[testClasses.Count];");
        sb.AppendLine("var testMethods = new Dictionary<Type, MethodInfo[]>(testClasses.Count);");
        sb.AppendLine($"var typeAttributes = new Dictionary<Type, Attribute[]>({typeAttributeCount});");
        sb.AppendLine($"var methodAttributes = new Dictionary<MethodInfo, Attribute[]>({methodAttributeCount});");
        sb.AppendLine($"var methodInvokers = new Dictionary<MethodInfo, Func<object?, object?[]?, object?>>({methodCount});");
        sb.AppendLine($"var constructorInvokers = new Dictionary<Type, {ConstructorInvokerInfoFullName}[]>(testClasses.Count);");
        sb.AppendLine($"var propertySetters = new Dictionary<PropertyInfo, Action<object?, object?>>({propertySetterCount});");
        sb.AppendLine("var descriptorTestMethods = new Dictionary<Type, MethodInfo[]>(testClasses.Count);");
        sb.AppendLine("var descriptorCompleteTypes = new List<Type>(testClasses.Count);");
        sb.AppendLine();

        using (sb.Block("for (int classIndex = 0; classIndex < testClasses.Count; classIndex++)"))
        {
            sb.AppendLine($"{RegistryNamespace}.TestClassReflectionInfo testClass = testClasses[classIndex];");
            sb.AppendLine("Type type = testClass.Type;");
            sb.AppendLine("types[classIndex] = type;");
            sb.AppendLine("MethodInfo[]? availableMethods = null;");
            sb.AppendLine("bool areDescriptorMethodsResolved = true;");
            using (sb.Block("if (testClass.AreAttributesComplete)"))
            {
                sb.AppendLine("typeAttributes[type] = testClass.Attributes;");
            }

            sb.AppendLine();

            sb.AppendLine($"var constructors = new {ConstructorInvokerInfoFullName}[testClass.Constructors.Count];");
            using (sb.Block("for (int constructorIndex = 0; constructorIndex < testClass.Constructors.Count; constructorIndex++)"))
            {
                sb.AppendLine($"{RegistryNamespace}.TestConstructorReflectionInfo constructor = testClass.Constructors[constructorIndex];");
                sb.AppendLine($"constructors[constructorIndex] = new {ConstructorInvokerInfoFullName}(constructor.ParameterTypes, constructor.Invoke);");
            }

            sb.AppendLine("constructorInvokers[type] = constructors;");
            sb.AppendLine();

            sb.AppendLine("var testMethodRoots = new List<MethodInfo>(testClass.Methods.Count);");
            sb.AppendLine("var descriptorMethodRoots = new List<MethodInfo>(testClass.Methods.Count);");
            using (sb.Block("for (int methodIndex = 0; methodIndex < testClass.Methods.Count; methodIndex++)"))
            {
                sb.AppendLine($"{RegistryNamespace}.TestMethodReflectionInfo method = testClass.Methods[methodIndex];");

                // Tolerate an unresolved member: skip its invoker (the adapter falls back to
                // reflection for that one method) rather than throwing out of the [ModuleInitializer],
                // which would fault registration for the whole assembly.
                sb.AppendLine("availableMethods ??= type.GetMethods(memberFlags);");
                sb.AppendLine("MethodInfo? methodInfo = ResolveMethod(availableMethods, method.Name, method.ParameterTypes);");
                using (sb.Block("if (methodInfo is not null)"))
                {
                    sb.AppendLine("methodInvokers[methodInfo] = method.Invoke;");
                    using (sb.Block("if (method.AreAttributesComplete)"))
                    {
                        sb.AppendLine("Attribute[] attributes = method.Attributes;");
                        using (sb.Block("if (method.IsAsync)"))
                        {
                            sb.AppendLine("object[] asyncStateMachineAttributes = methodInfo.GetCustomAttributes(typeof(AsyncStateMachineAttribute), inherit: false);");
                            sb.AppendLine("object[] debuggerStepThroughAttributes = methodInfo.GetCustomAttributes(typeof(DebuggerStepThroughAttribute), inherit: false);");
                            using (sb.Block("if (asyncStateMachineAttributes.Length + debuggerStepThroughAttributes.Length > 0)"))
                            {
                                sb.AppendLine("var attributesWithCompilerMetadata = new Attribute[attributes.Length + asyncStateMachineAttributes.Length + debuggerStepThroughAttributes.Length];");
                                sb.AppendLine("Array.Copy(attributes, attributesWithCompilerMetadata, attributes.Length);");
                                sb.AppendLine("Array.Copy(asyncStateMachineAttributes, 0, attributesWithCompilerMetadata, attributes.Length, asyncStateMachineAttributes.Length);");
                                sb.AppendLine("Array.Copy(debuggerStepThroughAttributes, 0, attributesWithCompilerMetadata, attributes.Length + asyncStateMachineAttributes.Length, debuggerStepThroughAttributes.Length);");
                                sb.AppendLine("attributes = attributesWithCompilerMetadata;");
                            }
                        }

                        sb.AppendLine("methodAttributes[methodInfo] = attributes;");
                    }

                    using (sb.Block("if (method.IsTestMethod)"))
                    {
                        sb.AppendLine("testMethodRoots.Add(methodInfo);");
                        using (sb.Block("if (testClass.SupportsGeneratedDescriptors && method.IsDescriptorSupported)"))
                        {
                            sb.AppendLine("descriptorMethodRoots.Add(methodInfo);");
                        }
                    }
                }

                using (sb.Block("else if (testClass.SupportsGeneratedDescriptors && method.IsDescriptorSupported)"))
                {
                    sb.AppendLine("areDescriptorMethodsResolved = false;");
                }

                // Register the source-generated DynamicData accessors so the runtime reads dynamic data
                // without reflecting over the declaring type (trim / Native AOT safe).
                using (sb.Block("for (int sourceIndex = 0; sourceIndex < method.DynamicDataSources.Count; sourceIndex++)"))
                {
                    sb.AppendLine($"{RegistryNamespace}.DynamicDataSourceReflectionInfo dynamicDataSource = method.DynamicDataSources[sourceIndex];");
                    sb.AppendLine($"{Constants.DynamicDataSourceResolverFullName}.RegisterDataProvider(dynamicDataSource.DeclaringType, dynamicDataSource.SourceName, dynamicDataSource.SourceType, dynamicDataSource.GetData);");
                    using (sb.Block("if (dynamicDataSource.DisplayNameDeclaringType is not null && dynamicDataSource.DisplayNameMethodName is not null && dynamicDataSource.GetDisplayName is not null)"))
                    {
                        sb.AppendLine($"{Constants.DynamicDataSourceResolverFullName}.RegisterDisplayNameProvider(dynamicDataSource.DisplayNameDeclaringType, dynamicDataSource.DisplayNameMethodName, dynamicDataSource.GetDisplayName);");
                    }
                }
            }

            sb.AppendLine("testMethods[type] = testMethodRoots.ToArray();");
            sb.AppendLine("descriptorTestMethods[type] = descriptorMethodRoots.ToArray();");
            using (sb.Block("if (testClass.AreGeneratedDescriptorsComplete && areDescriptorMethodsResolved)"))
            {
                sb.AppendLine("descriptorCompleteTypes.Add(type);");
            }

            sb.AppendLine();
            sb.AppendLine("PropertyInfo[]? availableProperties = null;");

            using (sb.Block("for (int propertyIndex = 0; propertyIndex < testClass.Properties.Count; propertyIndex++)"))
            {
                sb.AppendLine($"{RegistryNamespace}.TestPropertyReflectionInfo property = testClass.Properties[propertyIndex];");

                // Only publish a setter delegate when the property has a usable (public, non-init)
                // setter. For non-public / init-only setters the delegate would throw, so leave it
                // unregistered and let the adapter fall back to PropertyInfo.SetValue.
                using (sb.Block("if (property.HasPublicSetter)"))
                {
                    sb.AppendLine("availableProperties ??= type.GetProperties(memberFlags);");
                    sb.AppendLine("PropertyInfo? propertyInfo = ResolveProperty(availableProperties, property.Name);");
                    using (sb.Block("if (propertyInfo is not null)"))
                    {
                        sb.AppendLine("propertySetters[propertyInfo] = property.Set;");
                    }
                }
            }
        }

        sb.AppendLine();
        sb.AppendLine($"object[] assemblyAttributes = {RegistryNamespace}.MSTestReflectionMetadata.AssemblyAttributes;");
        sb.AppendLine($"{Constants.ReflectionMetadataHookFullName}.Register(assembly, types, testMethods, typeAttributes, assemblyAttributes, methodAttributes, methodInvokers, constructorInvokers, propertySetters, descriptorTestMethods, descriptorCompleteTypes.ToArray());");
    }

    private static void EmitResolveMethodHelper(IndentedStringBuilder sb)
    {
        sb.AppendLine("private static MethodInfo? ResolveMethod(MethodInfo[] availableMethods, string name, Type[] parameterTypes)");
        using (sb.Block(null))
        {
            using (sb.Block("foreach (MethodInfo candidate in availableMethods)"))
            {
                using (sb.Block("if (candidate.Name != name)"))
                {
                    sb.AppendLine("continue;");
                }

                sb.AppendLine();
                sb.AppendLine("ParameterInfo[] candidateParameters = candidate.GetParameters();");
                using (sb.Block("if (candidateParameters.Length != parameterTypes.Length)"))
                {
                    sb.AppendLine("continue;");
                }

                sb.AppendLine();
                sb.AppendLine("bool match = true;");
                using (sb.Block("for (int i = 0; i < candidateParameters.Length; i++)"))
                {
                    using (sb.Block("if (candidateParameters[i].ParameterType != parameterTypes[i])"))
                    {
                        sb.AppendLine("match = false;");
                        sb.AppendLine("break;");
                    }
                }

                sb.AppendLine();
                using (sb.Block("if (match)"))
                {
                    sb.AppendLine("return candidate;");
                }
            }

            sb.AppendLine();
            sb.AppendLine("// Unresolved: caller skips this member and the adapter falls back to reflection.");
            sb.AppendLine("return null;");
        }
    }

    private static void EmitResolvePropertyHelper(IndentedStringBuilder sb)
    {
        sb.AppendLine("private static PropertyInfo? ResolveProperty(PropertyInfo[] availableProperties, string name)");
        using (sb.Block(null))
        {
            using (sb.Block("foreach (PropertyInfo candidate in availableProperties)"))
            {
                using (sb.Block("if (candidate.Name == name)"))
                {
                    sb.AppendLine("return candidate;");
                }
            }

            sb.AppendLine();
            sb.AppendLine("// Unresolved: caller skips this member and the adapter falls back to reflection.");
            sb.AppendLine("return null;");
        }
    }
}
