parameters:
  symbolPublishingAdditionalParameters: ''

jobs:
- job: publish_symbols
  displayName: Symbols Publishing
  dependsOn: setupMaestroVars
  variables:
    - group: DotNet-Symbol-Server-Pats
    - name: AzDOProjectName
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOProjectName'] ]
    - name: AzDOPipelineId
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOPipelineId'] ]
    - name: AzDOBuildId
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOBuildId'] ]
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Build Assets
      continueOnError: true
      inputs:
        buildType: specific
        buildVersionToDownload: specific
        project: $(AzDOProjectName)
        pipeline: $(AzDOPipelineId)
        buildId: $(AzDOBuildId)
        downloadType: 'specific'
        itemPattern: |
          PdbArtifacts/**
          BlobArtifacts/**
        downloadPath: '$(Build.ArtifactStagingDirectory)'
        checkDownloadedFiles: true
        
    # This is necessary whenever we want to publish/restore to an AzDO private feed
    # Since sdk-task.ps1 tries to restore packages we need to do this authentication here
    # otherwise it'll complain about accessing a private feed.
    - task: NuGetAuthenticate@0
      displayName: 'Authenticate to AzDO Feeds'

    - task: PowerShell@2
      displayName: Enable cross-org publishing
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/enable-cross-org-publishing.ps1
        arguments: -token $(dn-bot-dnceng-artifact-feeds-rw)

    - task: PowerShell@2
      displayName: Publish
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/sdk-task.ps1
        arguments: -task PublishToSymbolServers -restore -msbuildEngine dotnet
          /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
          /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
          /p:PDBArtifactsDirectory='$(Build.ArtifactStagingDirectory)/PDBArtifacts/'
          /p:BlobBasePath='$(Build.ArtifactStagingDirectory)/BlobArtifacts/'
          /p:SymbolPublishingExclusionsFile='$(Build.SourcesDirectory)/eng/SymbolPublishingExclusionsFile.txt'
          /p:Configuration=Release
          /p:PublishToMSDL=false
          /p:PublishToSymWeb=true
          ${{ parameters.symbolPublishingAdditionalParameters }}

    - template: /eng/common/templates/steps/publish-logs.yml
      parameters:
        StageLabel: '${{ parameters.stageName }}'
        JobLabel: 'SymbolPublishing'
