jobs:
- job:
  displayName: Signing Validation
  dependsOn: setupMaestroVars
  variables:
    - template: /eng/publishing/v3/common-variables.yml
    - name: AzDOProjectName
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOProjectName'] ]
    - name: AzDOPipelineId
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOPipelineId'] ]
    - name: AzDOBuildId
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOBuildId'] ]
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Package Artifacts
      inputs:
        buildType: specific
        buildVersionToDownload: specific
        project: $(AzDOProjectName)
        pipeline: $(AzDOPipelineId)
        buildId: $(AzDOBuildId)
        artifactName: PackageArtifacts
        checkDownloadedFiles: true
        itemPattern: |
          **
          !**/Microsoft.SourceBuild.Intermediate.*.nupkg

    # This is necessary whenever we want to publish/restore to an AzDO private feed
    # Since sdk-task.ps1 tries to restore packages we need to do this authentication here
    # otherwise it'll complain about accessing a private feed.
    - task: NuGetAuthenticate@0
      displayName: 'Authenticate to AzDO Feeds'

    - task: PowerShell@2
      displayName: Enable cross-org publishing
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/enable-cross-org-publishing.ps1
        arguments: -token $(dn-bot-dnceng-artifact-feeds-rw)

    # Signing validation will optionally work with the buildmanifest file which is downloaded from
    # Azure DevOps above.
    - task: PowerShell@2
      displayName: Validate
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/sdk-task.ps1
        arguments: -task SigningValidation -restore -msbuildEngine vs
          /p:PackageBasePath='$(Build.ArtifactStagingDirectory)/PackageArtifacts'
          /p:SignCheckExclusionsFile='$(Build.SourcesDirectory)/eng/SignCheckExclusionsFile.txt'
          ${{ parameters.signingValidationAdditionalParameters }}

    - template: /eng/common/templates/steps/publish-logs.yml
      parameters:
        StageLabel: 'Validation'
        JobLabel: 'Signing'
