jobs:
- job:
  displayName: SourceLink Validation
  dependsOn: setupMaestroVars
  variables:
    - template: /eng/publishing/v3/common-variables.yml
    - name: AzDOProjectName
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOProjectName'] ]
    - name: AzDOPipelineId
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOPipelineId'] ]
    - name: AzDOBuildId
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOBuildId'] ]
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Blob Artifacts
      inputs:
        buildType: specific
        buildVersionToDownload: specific
        project: $(AzDOProjectName)
        pipeline: $(AzDOPipelineId)
        buildId: $(AzDOBuildId)
        artifactName: BlobArtifacts
        checkDownloadedFiles: true

    - task: PowerShell@2
      displayName: Validate
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/post-build/sourcelink-validation.ps1
        arguments: -InputPath $(Build.ArtifactStagingDirectory)/BlobArtifacts/ 
          -ExtractPath $(Agent.BuildDirectory)/Extract/ 
          -GHRepoName $(Build.Repository.Name) 
          -GHCommit $(Build.SourceVersion)
          -SourcelinkCliVersion $(SourceLinkCLIVersion)
      continueOnError: true
